/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_cost_ext_cost_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s3[9] = {1, 3, 0, 1, 2, 3, 0, 0, 0};
static const casadi_int casadi_s4[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s5[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s6[7] = {0, 1, 2, 3, 16, 17, 18};
static const casadi_int casadi_s7[7] = {0, 4, 8, 12, 16, 19, 22};
static const casadi_int casadi_s8[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s9[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s10[7] = {4, 5, 6, 7, 19, 20, 21};
static const casadi_int casadi_s11[7] = {1, 5, 9, 13, 17, 20, 23};
static const casadi_int casadi_s12[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s13[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s14[7] = {8, 9, 10, 11, 22, 23, 24};
static const casadi_int casadi_s15[7] = {2, 6, 10, 14, 18, 21, 24};
static const casadi_int casadi_s16[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s17[45] = {17, 17, 0, 4, 8, 12, 16, 19, 22, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 6, 4, 5, 6, 4, 5, 6};
static const casadi_int casadi_s18[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s19[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s20[3] = {0, 0, 0};
static const casadi_int casadi_s21[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s22[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s23[20] = {0, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* quadrotor_cost_ext_cost_fun_jac_hess:(i0[13],i1[4],i2[],i3[17])->(o0,o1[17],o2[17x17,25nz],o3[],o4[0x17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+22, *w20=w+39, *w21=w+42, *w22=w+55, *w23=w+58, *w24=w+67, *w25=w+71, *w26=w+75, *w27=w+79, *w28=w+95, *w29=w+111, *w30=w+120, *w31=w+145, *w35=w+157, *w36=w+164, *w47=w+166;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w6 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w7 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w8 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w9 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = input[3][15] */
  w17 = arg[3] ? arg[3][15] : 0;
  /* #18: @18 = input[3][16] */
  w18 = arg[3] ? arg[3][16] : 0;
  /* #19: @19 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w19;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #20: @20 = @19[:3] */
  for (rr=w20, ss=w19+0; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #21: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #22: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #23: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #24: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #25: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #26: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #27: @8 = input[0][6] */
  w8 = arg[0] ? arg[0][6] : 0;
  /* #28: @9 = input[0][7] */
  w9 = arg[0] ? arg[0][7] : 0;
  /* #29: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #30: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #31: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #32: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #33: @14 = input[0][12] */
  w14 = arg[0] ? arg[0][12] : 0;
  /* #34: @21 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14) */
  rr=w21;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #35: @22 = @21[:3] */
  for (rr=w22, ss=w21+0; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #36: @20 = (@20-@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) -= (*cs++);
  /* #37: @22 = @20' */
  casadi_copy(w20, 3, w22);
  /* #38: @23 = zeros(3x3) */
  casadi_clear(w23, 9);
  /* #39: @2 = 4.5 */
  w2 = 4.5000000000000000e+00;
  /* #40: (@23[0] = @2) */
  for (rr=w23+0, ss=(&w2); rr!=w23+1; rr+=1) *rr = *ss++;
  /* #41: @2 = 4.5 */
  w2 = 4.5000000000000000e+00;
  /* #42: (@23[4] = @2) */
  for (rr=w23+4, ss=(&w2); rr!=w23+5; rr+=1) *rr = *ss++;
  /* #43: @2 = 4.5 */
  w2 = 4.5000000000000000e+00;
  /* #44: (@23[8] = @2) */
  for (rr=w23+8, ss=(&w2); rr!=w23+9; rr+=1) *rr = *ss++;
  /* #45: @1 = mac(@22,@23,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w22+j, tt=w23+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #46: @0 = mac(@1,@20,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w20+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #47: @2 = 0 */
  w2 = 0.;
  /* #48: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #49: @25 = @19[13:17] */
  for (rr=w25, ss=w19+13; ss!=w19+17; ss+=1) *rr++ = *ss;
  /* #50: @3 = input[1][0] */
  w3 = arg[1] ? arg[1][0] : 0;
  /* #51: @4 = input[1][1] */
  w4 = arg[1] ? arg[1][1] : 0;
  /* #52: @5 = input[1][2] */
  w5 = arg[1] ? arg[1][2] : 0;
  /* #53: @6 = input[1][3] */
  w6 = arg[1] ? arg[1][3] : 0;
  /* #54: @26 = vertcat(@3, @4, @5, @6) */
  rr=w26;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  /* #55: @25 = (@25-@26) */
  for (i=0, rr=w25, cs=w26; i<4; ++i) (*rr++) -= (*cs++);
  /* #56: @26 = @25' */
  casadi_copy(w25, 4, w26);
  /* #57: @27 = zeros(4x4) */
  casadi_clear(w27, 16);
  /* #58: @3 = 0.671141 */
  w3 = 6.7114093959731547e-01;
  /* #59: (@27[0] = @3) */
  for (rr=w27+0, ss=(&w3); rr!=w27+1; rr+=1) *rr = *ss++;
  /* #60: @3 = 600 */
  w3 = 600.;
  /* #61: (@27[5] = @3) */
  for (rr=w27+5, ss=(&w3); rr!=w27+6; rr+=1) *rr = *ss++;
  /* #62: @3 = 600 */
  w3 = 600.;
  /* #63: (@27[10] = @3) */
  for (rr=w27+10, ss=(&w3); rr!=w27+11; rr+=1) *rr = *ss++;
  /* #64: @3 = 600 */
  w3 = 600.;
  /* #65: (@27[15] = @3) */
  for (rr=w27+15, ss=(&w3); rr!=w27+16; rr+=1) *rr = *ss++;
  /* #66: @24 = mac(@26,@27,@24) */
  for (i=0, rr=w24; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w26+j, tt=w27+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #67: @2 = mac(@24,@25,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w25+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #68: @0 = (@0+@2) */
  w0 += w2;
  /* #69: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #70: @24 = @24' */
  /* #71: @26 = zeros(1x4) */
  casadi_clear(w26, 4);
  /* #72: @25 = @25' */
  /* #73: @28 = @27' */
  for (i=0, rr=w28, cs=w27; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #74: @26 = mac(@25,@28,@26) */
  for (i=0, rr=w26; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w25+j, tt=w28+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #75: @26 = @26' */
  /* #76: @24 = (@24+@26) */
  for (i=0, rr=w24, cs=w26; i<4; ++i) (*rr++) += (*cs++);
  /* #77: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<4; ++i) *rr++ = (- *cs++ );
  /* #78: {@0, @2, @3, @4} = vertsplit(@24) */
  w0 = w24[0];
  w2 = w24[1];
  w3 = w24[2];
  w4 = w24[3];
  /* #79: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #80: output[1][1] = @2 */
  if (res[1]) res[1][1] = w2;
  /* #81: output[1][2] = @3 */
  if (res[1]) res[1][2] = w3;
  /* #82: output[1][3] = @4 */
  if (res[1]) res[1][3] = w4;
  /* #83: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #84: @1 = @1' */
  /* #85: @22 = zeros(1x3) */
  casadi_clear(w22, 3);
  /* #86: @20 = @20' */
  /* #87: @29 = @23' */
  for (i=0, rr=w29, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #88: @22 = mac(@20,@29,@22) */
  for (i=0, rr=w22; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w20+j, tt=w29+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #89: @22 = @22' */
  /* #90: @1 = (@1+@22) */
  for (i=0, rr=w1, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #91: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #92: (@21[:3] += @1) */
  for (rr=w21+0, ss=w1; rr!=w21+3; rr+=1) *rr += *ss++;
  /* #93: {@4, @3, @2, @0, @5, @6, @7, @8, @9, @10, @11, @12, @13} = vertsplit(@21) */
  w4 = w21[0];
  w3 = w21[1];
  w2 = w21[2];
  w0 = w21[3];
  w5 = w21[4];
  w6 = w21[5];
  w7 = w21[6];
  w8 = w21[7];
  w9 = w21[8];
  w10 = w21[9];
  w11 = w21[10];
  w12 = w21[11];
  w13 = w21[12];
  /* #94: output[1][4] = @4 */
  if (res[1]) res[1][4] = w4;
  /* #95: output[1][5] = @3 */
  if (res[1]) res[1][5] = w3;
  /* #96: output[1][6] = @2 */
  if (res[1]) res[1][6] = w2;
  /* #97: output[1][7] = @0 */
  if (res[1]) res[1][7] = w0;
  /* #98: output[1][8] = @5 */
  if (res[1]) res[1][8] = w5;
  /* #99: output[1][9] = @6 */
  if (res[1]) res[1][9] = w6;
  /* #100: output[1][10] = @7 */
  if (res[1]) res[1][10] = w7;
  /* #101: output[1][11] = @8 */
  if (res[1]) res[1][11] = w8;
  /* #102: output[1][12] = @9 */
  if (res[1]) res[1][12] = w9;
  /* #103: output[1][13] = @10 */
  if (res[1]) res[1][13] = w10;
  /* #104: output[1][14] = @11 */
  if (res[1]) res[1][14] = w11;
  /* #105: output[1][15] = @12 */
  if (res[1]) res[1][15] = w12;
  /* #106: output[1][16] = @13 */
  if (res[1]) res[1][16] = w13;
  /* #107: @30 = zeros(17x17,25nz) */
  casadi_clear(w30, 25);
  /* #108: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #109: @31 = ones(17x1,12nz) */
  casadi_fill(w31, 12, 1.);
  /* #110: {@13, NULL, NULL, NULL, @12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@31) */
  w13 = w31[0];
  w12 = w31[1];
  /* #111: @32 = 00 */
  /* #112: @33 = 00 */
  /* #113: @34 = 00 */
  /* #114: @11 = vertcat(@13, @32, @33, @34) */
  rr=(&w11);
  *rr++ = w13;
  /* #115: @11 = (-@11) */
  w11 = (- w11 );
  /* #116: @13 = @11' */
  casadi_copy((&w11), 1, (&w13));
  /* #117: @24 = mac(@13,@27,@24) */
  casadi_mtimes((&w13), casadi_s2, w27, casadi_s1, w24, casadi_s0, w, 0);
  /* #118: @24 = @24' */
  /* #119: @26 = zeros(1x4) */
  casadi_clear(w26, 4);
  /* #120: @11 = @11' */
  /* #121: @26 = mac(@11,@28,@26) */
  casadi_mtimes((&w11), casadi_s2, w28, casadi_s1, w26, casadi_s0, w, 0);
  /* #122: @26 = @26' */
  /* #123: @24 = (@24+@26) */
  for (i=0, rr=w24, cs=w26; i<4; ++i) (*rr++) += (*cs++);
  /* #124: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<4; ++i) *rr++ = (- *cs++ );
  /* #125: {@11, @13, @10, @9} = vertsplit(@24) */
  w11 = w24[0];
  w13 = w24[1];
  w10 = w24[2];
  w9 = w24[3];
  /* #126: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #127: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #128: @12 = sparsity_cast(@12) */
  /* #129: @12 = (-@12) */
  w12 = (- w12 );
  /* #130: @8 = @12' */
  casadi_copy((&w12), 1, (&w8));
  /* #131: @1 = mac(@8,@23,@1) */
  casadi_mtimes((&w8), casadi_s5, w23, casadi_s4, w1, casadi_s3, w, 0);
  /* #132: @1 = @1' */
  /* #133: @22 = zeros(1x3) */
  casadi_clear(w22, 3);
  /* #134: @12 = @12' */
  /* #135: @22 = mac(@12,@29,@22) */
  casadi_mtimes((&w12), casadi_s5, w29, casadi_s4, w22, casadi_s3, w, 0);
  /* #136: @22 = @22' */
  /* #137: @1 = (@1+@22) */
  for (i=0, rr=w1, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #138: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #139: (@21[:3] += @1) */
  for (rr=w21+0, ss=w1; rr!=w21+3; rr+=1) *rr += *ss++;
  /* #140: {@12, @8, @7, @6, @5, @0, @2, @3, @4, @14, @15, @16, @17} = vertsplit(@21) */
  w12 = w21[0];
  w8 = w21[1];
  w7 = w21[2];
  w6 = w21[3];
  w5 = w21[4];
  w0 = w21[5];
  w2 = w21[6];
  w3 = w21[7];
  w4 = w21[8];
  w14 = w21[9];
  w15 = w21[10];
  w16 = w21[11];
  w17 = w21[12];
  /* #141: @19 = vertcat(@11, @13, @10, @9, @12, @8, @7, @6, @5, @0, @2, @3, @4, @14, @15, @16, @17) */
  rr=w19;
  *rr++ = w11;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w9;
  *rr++ = w12;
  *rr++ = w8;
  *rr++ = w7;
  *rr++ = w6;
  *rr++ = w5;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  /* #142: @35 = @19[:7] */
  for (rr=w35, ss=w19+0; ss!=w19+7; ss+=1) *rr++ = *ss;
  /* #143: (@30[0, 1, 2, 3, 16, 17, 18] = @35) */
  for (cii=casadi_s6, rr=w30, ss=w35; cii!=casadi_s6+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #144: @35 = @19[:7] */
  for (rr=w35, ss=w19+0; ss!=w19+7; ss+=1) *rr++ = *ss;
  /* #145: (@30[0, 4, 8, 12, 16, 19, 22] = @35) */
  for (cii=casadi_s7, rr=w30, ss=w35; cii!=casadi_s7+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #146: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #147: @32 = 00 */
  /* #148: @36 = ones(17x1,2nz) */
  casadi_fill(w36, 2, 1.);
  /* #149: {NULL, @11, NULL, NULL, NULL, @13, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@36) */
  w11 = w36[0];
  w13 = w36[1];
  /* #150: @33 = 00 */
  /* #151: @34 = 00 */
  /* #152: @10 = vertcat(@32, @11, @33, @34) */
  rr=(&w10);
  *rr++ = w11;
  /* #153: @10 = (-@10) */
  w10 = (- w10 );
  /* #154: @11 = @10' */
  casadi_copy((&w10), 1, (&w11));
  /* #155: @24 = mac(@11,@27,@24) */
  casadi_mtimes((&w11), casadi_s8, w27, casadi_s1, w24, casadi_s0, w, 0);
  /* #156: @24 = @24' */
  /* #157: @26 = zeros(1x4) */
  casadi_clear(w26, 4);
  /* #158: @10 = @10' */
  /* #159: @26 = mac(@10,@28,@26) */
  casadi_mtimes((&w10), casadi_s8, w28, casadi_s1, w26, casadi_s0, w, 0);
  /* #160: @26 = @26' */
  /* #161: @24 = (@24+@26) */
  for (i=0, rr=w24, cs=w26; i<4; ++i) (*rr++) += (*cs++);
  /* #162: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<4; ++i) *rr++ = (- *cs++ );
  /* #163: {@10, @11, @9, @12} = vertsplit(@24) */
  w10 = w24[0];
  w11 = w24[1];
  w9 = w24[2];
  w12 = w24[3];
  /* #164: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #165: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #166: @13 = sparsity_cast(@13) */
  /* #167: @13 = (-@13) */
  w13 = (- w13 );
  /* #168: @8 = @13' */
  casadi_copy((&w13), 1, (&w8));
  /* #169: @1 = mac(@8,@23,@1) */
  casadi_mtimes((&w8), casadi_s9, w23, casadi_s4, w1, casadi_s3, w, 0);
  /* #170: @1 = @1' */
  /* #171: @22 = zeros(1x3) */
  casadi_clear(w22, 3);
  /* #172: @13 = @13' */
  /* #173: @22 = mac(@13,@29,@22) */
  casadi_mtimes((&w13), casadi_s9, w29, casadi_s4, w22, casadi_s3, w, 0);
  /* #174: @22 = @22' */
  /* #175: @1 = (@1+@22) */
  for (i=0, rr=w1, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #176: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #177: (@21[:3] += @1) */
  for (rr=w21+0, ss=w1; rr!=w21+3; rr+=1) *rr += *ss++;
  /* #178: {@13, @8, @7, @6, @5, @0, @2, @3, @4, @14, @15, @16, @17} = vertsplit(@21) */
  w13 = w21[0];
  w8 = w21[1];
  w7 = w21[2];
  w6 = w21[3];
  w5 = w21[4];
  w0 = w21[5];
  w2 = w21[6];
  w3 = w21[7];
  w4 = w21[8];
  w14 = w21[9];
  w15 = w21[10];
  w16 = w21[11];
  w17 = w21[12];
  /* #179: @19 = vertcat(@10, @11, @9, @12, @13, @8, @7, @6, @5, @0, @2, @3, @4, @14, @15, @16, @17) */
  rr=w19;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w9;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w8;
  *rr++ = w7;
  *rr++ = w6;
  *rr++ = w5;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  /* #180: @35 = @19[:7] */
  for (rr=w35, ss=w19+0; ss!=w19+7; ss+=1) *rr++ = *ss;
  /* #181: (@30[4, 5, 6, 7, 19, 20, 21] = @35) */
  for (cii=casadi_s10, rr=w30, ss=w35; cii!=casadi_s10+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #182: @35 = @19[:7] */
  for (rr=w35, ss=w19+0; ss!=w19+7; ss+=1) *rr++ = *ss;
  /* #183: (@30[1, 5, 9, 13, 17, 20, 23] = @35) */
  for (cii=casadi_s11, rr=w30, ss=w35; cii!=casadi_s11+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #184: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #185: @32 = 00 */
  /* #186: @33 = 00 */
  /* #187: @36 = ones(17x1,2nz) */
  casadi_fill(w36, 2, 1.);
  /* #188: {NULL, NULL, @10, NULL, NULL, NULL, @11, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@36) */
  w10 = w36[0];
  w11 = w36[1];
  /* #189: @34 = 00 */
  /* #190: @9 = vertcat(@32, @33, @10, @34) */
  rr=(&w9);
  *rr++ = w10;
  /* #191: @9 = (-@9) */
  w9 = (- w9 );
  /* #192: @10 = @9' */
  casadi_copy((&w9), 1, (&w10));
  /* #193: @24 = mac(@10,@27,@24) */
  casadi_mtimes((&w10), casadi_s12, w27, casadi_s1, w24, casadi_s0, w, 0);
  /* #194: @24 = @24' */
  /* #195: @26 = zeros(1x4) */
  casadi_clear(w26, 4);
  /* #196: @9 = @9' */
  /* #197: @26 = mac(@9,@28,@26) */
  casadi_mtimes((&w9), casadi_s12, w28, casadi_s1, w26, casadi_s0, w, 0);
  /* #198: @26 = @26' */
  /* #199: @24 = (@24+@26) */
  for (i=0, rr=w24, cs=w26; i<4; ++i) (*rr++) += (*cs++);
  /* #200: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<4; ++i) *rr++ = (- *cs++ );
  /* #201: {@9, @10, @12, @13} = vertsplit(@24) */
  w9 = w24[0];
  w10 = w24[1];
  w12 = w24[2];
  w13 = w24[3];
  /* #202: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #203: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #204: @11 = sparsity_cast(@11) */
  /* #205: @11 = (-@11) */
  w11 = (- w11 );
  /* #206: @8 = @11' */
  casadi_copy((&w11), 1, (&w8));
  /* #207: @1 = mac(@8,@23,@1) */
  casadi_mtimes((&w8), casadi_s13, w23, casadi_s4, w1, casadi_s3, w, 0);
  /* #208: @1 = @1' */
  /* #209: @22 = zeros(1x3) */
  casadi_clear(w22, 3);
  /* #210: @11 = @11' */
  /* #211: @22 = mac(@11,@29,@22) */
  casadi_mtimes((&w11), casadi_s13, w29, casadi_s4, w22, casadi_s3, w, 0);
  /* #212: @22 = @22' */
  /* #213: @1 = (@1+@22) */
  for (i=0, rr=w1, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #214: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #215: (@21[:3] += @1) */
  for (rr=w21+0, ss=w1; rr!=w21+3; rr+=1) *rr += *ss++;
  /* #216: {@11, @8, @7, @6, @5, @0, @2, @3, @4, @14, @15, @16, @17} = vertsplit(@21) */
  w11 = w21[0];
  w8 = w21[1];
  w7 = w21[2];
  w6 = w21[3];
  w5 = w21[4];
  w0 = w21[5];
  w2 = w21[6];
  w3 = w21[7];
  w4 = w21[8];
  w14 = w21[9];
  w15 = w21[10];
  w16 = w21[11];
  w17 = w21[12];
  /* #217: @19 = vertcat(@9, @10, @12, @13, @11, @8, @7, @6, @5, @0, @2, @3, @4, @14, @15, @16, @17) */
  rr=w19;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w11;
  *rr++ = w8;
  *rr++ = w7;
  *rr++ = w6;
  *rr++ = w5;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  /* #218: @35 = @19[:7] */
  for (rr=w35, ss=w19+0; ss!=w19+7; ss+=1) *rr++ = *ss;
  /* #219: (@30[8, 9, 10, 11, 22, 23, 24] = @35) */
  for (cii=casadi_s14, rr=w30, ss=w35; cii!=casadi_s14+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #220: @35 = @19[:7] */
  for (rr=w35, ss=w19+0; ss!=w19+7; ss+=1) *rr++ = *ss;
  /* #221: (@30[2, 6, 10, 14, 18, 21, 24] = @35) */
  for (cii=casadi_s15, rr=w30, ss=w35; cii!=casadi_s15+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #222: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #223: @32 = 00 */
  /* #224: @33 = 00 */
  /* #225: @34 = 00 */
  /* #226: @9 = ones(17x1,1nz) */
  w9 = 1.;
  /* #227: {NULL, NULL, NULL, @10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@9) */
  w10 = w9;
  /* #228: @9 = vertcat(@32, @33, @34, @10) */
  rr=(&w9);
  *rr++ = w10;
  /* #229: @9 = (-@9) */
  w9 = (- w9 );
  /* #230: @10 = @9' */
  casadi_copy((&w9), 1, (&w10));
  /* #231: @24 = mac(@10,@27,@24) */
  casadi_mtimes((&w10), casadi_s16, w27, casadi_s1, w24, casadi_s0, w, 0);
  /* #232: @24 = @24' */
  /* #233: @26 = zeros(1x4) */
  casadi_clear(w26, 4);
  /* #234: @9 = @9' */
  /* #235: @26 = mac(@9,@28,@26) */
  casadi_mtimes((&w9), casadi_s16, w28, casadi_s1, w26, casadi_s0, w, 0);
  /* #236: @26 = @26' */
  /* #237: @24 = (@24+@26) */
  for (i=0, rr=w24, cs=w26; i<4; ++i) (*rr++) += (*cs++);
  /* #238: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<4; ++i) *rr++ = (- *cs++ );
  /* #239: {@9, @10, @12, @13} = vertsplit(@24) */
  w9 = w24[0];
  w10 = w24[1];
  w12 = w24[2];
  w13 = w24[3];
  /* #240: @32 = 00 */
  /* #241: @33 = 00 */
  /* #242: @34 = 00 */
  /* #243: @37 = 00 */
  /* #244: @38 = 00 */
  /* #245: @39 = 00 */
  /* #246: @40 = 00 */
  /* #247: @41 = 00 */
  /* #248: @42 = 00 */
  /* #249: @43 = 00 */
  /* #250: @44 = 00 */
  /* #251: @45 = 00 */
  /* #252: @46 = 00 */
  /* #253: @24 = vertcat(@9, @10, @12, @13, @32, @33, @34, @37, @38, @39, @40, @41, @42, @43, @44, @45, @46) */
  rr=w24;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w13;
  /* #254: @26 = @24[:4] */
  for (rr=w26, ss=w24+0; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #255: (@30[12:16] = @26) */
  for (rr=w30+12, ss=w26; rr!=w30+16; rr+=1) *rr = *ss++;
  /* #256: @26 = @24[:4] */
  for (rr=w26, ss=w24+0; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #257: (@30[3:19:4] = @26) */
  for (rr=w30+3, ss=w26; rr!=w30+19; rr+=4) *rr = *ss++;
  /* #258: @47 = @30' */
  casadi_trans(w30,casadi_s17, w47, casadi_s17, iw);
  /* #259: output[2][0] = @47 */
  casadi_copy(w47, 25, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_cost_ext_cost_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s18;
    case 1: return casadi_s19;
    case 2: return casadi_s20;
    case 3: return casadi_s21;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s22;
    case 1: return casadi_s21;
    case 2: return casadi_s17;
    case 3: return casadi_s20;
    case 4: return casadi_s23;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21;
  if (sz_res) *sz_res = 22;
  if (sz_iw) *sz_iw = 18;
  if (sz_w) *sz_w = 191;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 22*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 18*sizeof(casadi_int);
  if (sz_w) *sz_w = 191*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
