/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_impl_dae_fun_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s27 CASADI_PREFIX(s27)
#define casadi_s28 CASADI_PREFIX(s28)
#define casadi_s29 CASADI_PREFIX(s29)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s30 CASADI_PREFIX(s30)
#define casadi_s31 CASADI_PREFIX(s31)
#define casadi_s32 CASADI_PREFIX(s32)
#define casadi_s33 CASADI_PREFIX(s33)
#define casadi_s34 CASADI_PREFIX(s34)
#define casadi_s35 CASADI_PREFIX(s35)
#define casadi_s36 CASADI_PREFIX(s36)
#define casadi_s37 CASADI_PREFIX(s37)
#define casadi_s38 CASADI_PREFIX(s38)
#define casadi_s39 CASADI_PREFIX(s39)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s40 CASADI_PREFIX(s40)
#define casadi_s41 CASADI_PREFIX(s41)
#define casadi_s42 CASADI_PREFIX(s42)
#define casadi_s43 CASADI_PREFIX(s43)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[3] = {0, 1, 2};
static const casadi_int casadi_s1[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[12] = {3, 3, 0, 3, 5, 6, 0, 1, 2, 1, 2, 2};
static const casadi_int casadi_s3[12] = {3, 3, 0, 1, 3, 6, 0, 0, 1, 0, 1, 2};
static const casadi_int casadi_s4[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s5[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s6[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s7[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s8[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s9[11] = {4, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3};
static const casadi_int casadi_s10[10] = {0, 1, 2, 3, 7, 11, 15, 22, 29, 36};
static const casadi_int casadi_s11[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s12[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s13[11] = {4, 4, 0, 1, 2, 3, 4, 1, 0, 3, 2};
static const casadi_int casadi_s14[4] = {1, 0, 3, 2};
static const casadi_int casadi_s15[7] = {4, 8, 12, 16, 23, 30, 37};
static const casadi_int casadi_s16[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s17[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s18[11] = {4, 4, 0, 1, 2, 3, 4, 2, 3, 0, 1};
static const casadi_int casadi_s19[4] = {2, 3, 0, 1};
static const casadi_int casadi_s20[7] = {5, 9, 13, 17, 24, 31, 38};
static const casadi_int casadi_s21[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s22[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s23[11] = {4, 4, 0, 1, 2, 3, 4, 3, 2, 1, 0};
static const casadi_int casadi_s24[4] = {3, 2, 1, 0};
static const casadi_int casadi_s25[7] = {6, 10, 14, 18, 25, 32, 39};
static const casadi_int casadi_s26[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s27[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s28[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s29[7] = {19, 26, 33, 40, 43, 46, 49};
static const casadi_int casadi_s30[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s31[7] = {20, 27, 34, 41, 44, 47, 50};
static const casadi_int casadi_s32[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s33[7] = {21, 28, 35, 42, 45, 48, 51};
static const casadi_int casadi_s34[68] = {13, 13, 0, 0, 0, 0, 1, 2, 3, 10, 17, 24, 31, 38, 45, 52, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 3, 4, 5, 6, 7, 8, 9, 3, 4, 5, 6, 7, 8, 9, 3, 4, 5, 6, 7, 8, 9, 6, 7, 8, 9, 10, 11, 12, 6, 7, 8, 9, 10, 11, 12, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s35[68] = {13, 13, 0, 1, 2, 3, 7, 11, 15, 22, 29, 36, 43, 46, 49, 52, 3, 4, 5, 6, 7, 8, 9, 6, 7, 8, 9, 6, 7, 8, 9, 6, 7, 8, 9, 10, 11, 12, 6, 7, 8, 9, 10, 11, 12, 6, 7, 8, 9, 10, 11, 12, 6, 7, 8, 9, 10, 11, 12, 10, 11, 12, 10, 11, 12, 10, 11, 12};
static const casadi_int casadi_s36[29] = {13, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s37[6] = {0, 1, 2, 3, 6, 9};
static const casadi_int casadi_s38[19] = {13, 4, 0, 3, 6, 9, 12, 3, 4, 5, 10, 11, 12, 10, 11, 12, 10, 11, 12};
static const casadi_int casadi_s39[28] = {4, 13, 0, 0, 0, 0, 1, 2, 3, 3, 3, 3, 3, 6, 9, 12, 0, 0, 0, 1, 2, 3, 1, 2, 3, 1, 2, 3};
static const casadi_int casadi_s40[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s41[3] = {0, 0, 0};
static const casadi_int casadi_s42[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s43[3] = {13, 0, 0};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};

/* quadrotor_impl_dae_fun_jac_x_xdot_u_z:(i0[13],i1[13],i2[4],i3[],i4[],i5[17])->(o0[13],o1[13x13,52nz],o2[13x13,13nz],o3[13x4,12nz],o4[13x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cr, *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, *w13=w+17, *w14=w+30, *w15=w+43, *w16=w+46, *w17=w+49, *w18=w+53, *w19=w+57, w20, w21, w22, w23, *w24=w+65, *w25=w+68, *w26=w+71, *w27=w+74, *w28=w+83, *w29=w+92, *w30=w+96, *w31=w+100, *w32=w+104, *w33=w+108, *w34=w+112, *w35=w+128, w36, w37, *w38=w+146, *w39=w+149, *w40=w+152, w41, w42, w43, w44, *w45=w+159, *w46=w+211, w47, w48, w49, w56, w57, w58, w59, w60, w61, w62, w63, w64, w65, w66, w67, *w68=w+233, *w69=w+242, *w70=w+251, *w71=w+261, w72, w73, w74, *w75=w+274, *w76=w+281, *w77=w+333, *w78=w+345, *w79=w+347, *w80=w+353, *w81=w+359;
  /* #0: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #1: @1 = input[1][1] */
  w1 = arg[1] ? arg[1][1] : 0;
  /* #2: @2 = input[1][2] */
  w2 = arg[1] ? arg[1][2] : 0;
  /* #3: @3 = input[1][3] */
  w3 = arg[1] ? arg[1][3] : 0;
  /* #4: @4 = input[1][4] */
  w4 = arg[1] ? arg[1][4] : 0;
  /* #5: @5 = input[1][5] */
  w5 = arg[1] ? arg[1][5] : 0;
  /* #6: @6 = input[1][6] */
  w6 = arg[1] ? arg[1][6] : 0;
  /* #7: @7 = input[1][7] */
  w7 = arg[1] ? arg[1][7] : 0;
  /* #8: @8 = input[1][8] */
  w8 = arg[1] ? arg[1][8] : 0;
  /* #9: @9 = input[1][9] */
  w9 = arg[1] ? arg[1][9] : 0;
  /* #10: @10 = input[1][10] */
  w10 = arg[1] ? arg[1][10] : 0;
  /* #11: @11 = input[1][11] */
  w11 = arg[1] ? arg[1][11] : 0;
  /* #12: @12 = input[1][12] */
  w12 = arg[1] ? arg[1][12] : 0;
  /* #13: @13 = vertcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12) */
  rr=w13;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #14: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #15: @1 = input[0][1] */
  w1 = arg[0] ? arg[0][1] : 0;
  /* #16: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #17: @3 = input[0][3] */
  w3 = arg[0] ? arg[0][3] : 0;
  /* #18: @4 = input[0][4] */
  w4 = arg[0] ? arg[0][4] : 0;
  /* #19: @5 = input[0][5] */
  w5 = arg[0] ? arg[0][5] : 0;
  /* #20: @6 = input[0][6] */
  w6 = arg[0] ? arg[0][6] : 0;
  /* #21: @7 = input[0][7] */
  w7 = arg[0] ? arg[0][7] : 0;
  /* #22: @8 = input[0][8] */
  w8 = arg[0] ? arg[0][8] : 0;
  /* #23: @9 = input[0][9] */
  w9 = arg[0] ? arg[0][9] : 0;
  /* #24: @10 = input[0][10] */
  w10 = arg[0] ? arg[0][10] : 0;
  /* #25: @11 = input[0][11] */
  w11 = arg[0] ? arg[0][11] : 0;
  /* #26: @12 = input[0][12] */
  w12 = arg[0] ? arg[0][12] : 0;
  /* #27: @14 = vertcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12) */
  rr=w14;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #28: @15 = @14[3:6] */
  for (rr=w15, ss=w14+3; ss!=w14+6; ss+=1) *rr++ = *ss;
  /* #29: @0 = input[2][0] */
  w0 = arg[2] ? arg[2][0] : 0;
  /* #30: @16 = zeros(3x1) */
  casadi_clear(w16, 3);
  /* #31: @17 = @14[6:10] */
  for (rr=w17, ss=w14+6; ss!=w14+10; ss+=1) *rr++ = *ss;
  /* #32: @1 = 0 */
  w1 = 0.;
  /* #33: @18 = @17' */
  casadi_copy(w17, 4, w18);
  /* #34: @1 = mac(@18,@17,@1) */
  for (i=0, rr=(&w1); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w18+j, tt=w17+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #35: @19 = (@17/@1) */
  for (i=0, rr=w19, cr=w17; i<4; ++i) (*rr++)  = ((*cr++)/w1);
  /* #36: @2 = @19[0] */
  for (rr=(&w2), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #37: @3 = sq(@2) */
  w3 = casadi_sq( w2 );
  /* #38: @4 = @19[1] */
  for (rr=(&w4), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #39: @5 = sq(@4) */
  w5 = casadi_sq( w4 );
  /* #40: @3 = (@3+@5) */
  w3 += w5;
  /* #41: @5 = @19[2] */
  for (rr=(&w5), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #42: @20 = sq(@5) */
  w20 = casadi_sq( w5 );
  /* #43: @3 = (@3-@20) */
  w3 -= w20;
  /* #44: @20 = @19[3] */
  for (rr=(&w20), ss=w19+3; ss!=w19+4; ss+=1) *rr++ = *ss;
  /* #45: @21 = sq(@20) */
  w21 = casadi_sq( w20 );
  /* #46: @3 = (@3-@21) */
  w3 -= w21;
  /* #47: @21 = (@4*@5) */
  w21  = (w4*w5);
  /* #48: @22 = (@2*@20) */
  w22  = (w2*w20);
  /* #49: @21 = (@21-@22) */
  w21 -= w22;
  /* #50: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #51: @22 = (@4*@20) */
  w22  = (w4*w20);
  /* #52: @23 = (@2*@5) */
  w23  = (w2*w5);
  /* #53: @22 = (@22+@23) */
  w22 += w23;
  /* #54: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #55: @24 = horzcat(@3, @21, @22) */
  rr=w24;
  *rr++ = w3;
  *rr++ = w21;
  *rr++ = w22;
  /* #56: @24 = @24' */
  /* #57: @3 = (@4*@5) */
  w3  = (w4*w5);
  /* #58: @21 = (@2*@20) */
  w21  = (w2*w20);
  /* #59: @3 = (@3+@21) */
  w3 += w21;
  /* #60: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #61: @21 = sq(@2) */
  w21 = casadi_sq( w2 );
  /* #62: @22 = sq(@5) */
  w22 = casadi_sq( w5 );
  /* #63: @21 = (@21+@22) */
  w21 += w22;
  /* #64: @22 = sq(@4) */
  w22 = casadi_sq( w4 );
  /* #65: @21 = (@21-@22) */
  w21 -= w22;
  /* #66: @22 = sq(@20) */
  w22 = casadi_sq( w20 );
  /* #67: @21 = (@21-@22) */
  w21 -= w22;
  /* #68: @22 = (@5*@20) */
  w22  = (w5*w20);
  /* #69: @23 = (@2*@4) */
  w23  = (w2*w4);
  /* #70: @22 = (@22-@23) */
  w22 -= w23;
  /* #71: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #72: @25 = horzcat(@3, @21, @22) */
  rr=w25;
  *rr++ = w3;
  *rr++ = w21;
  *rr++ = w22;
  /* #73: @25 = @25' */
  /* #74: @3 = (@4*@20) */
  w3  = (w4*w20);
  /* #75: @21 = (@2*@5) */
  w21  = (w2*w5);
  /* #76: @3 = (@3-@21) */
  w3 -= w21;
  /* #77: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #78: @21 = (@5*@20) */
  w21  = (w5*w20);
  /* #79: @22 = (@2*@4) */
  w22  = (w2*w4);
  /* #80: @21 = (@21+@22) */
  w21 += w22;
  /* #81: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #82: @22 = sq(@2) */
  w22 = casadi_sq( w2 );
  /* #83: @23 = sq(@20) */
  w23 = casadi_sq( w20 );
  /* #84: @22 = (@22+@23) */
  w22 += w23;
  /* #85: @23 = sq(@4) */
  w23 = casadi_sq( w4 );
  /* #86: @22 = (@22-@23) */
  w22 -= w23;
  /* #87: @23 = sq(@5) */
  w23 = casadi_sq( w5 );
  /* #88: @22 = (@22-@23) */
  w22 -= w23;
  /* #89: @26 = horzcat(@3, @21, @22) */
  rr=w26;
  *rr++ = w3;
  *rr++ = w21;
  *rr++ = w22;
  /* #90: @26 = @26' */
  /* #91: @27 = horzcat(@24, @25, @26) */
  rr=w27;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<3; ++i) *rr++ = *cs++;
  /* #92: @28 = @27' */
  for (i=0, rr=w28, cs=w27; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #93: @24 = zeros(3x1) */
  casadi_clear(w24, 3);
  /* #94: @3 = 1 */
  w3 = 1.;
  /* #95: (@24[2] = @3) */
  for (rr=w24+2, ss=(&w3); rr!=w24+3; rr+=1) *rr = *ss++;
  /* #96: @16 = mac(@28,@24,@16) */
  for (i=0, rr=w16; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w28+j, tt=w24+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #97: @25 = (@0*@16) */
  for (i=0, rr=w25, cs=w16; i<3; ++i) (*rr++)  = (w0*(*cs++));
  /* #98: @3 = 9.8 */
  w3 = 9.8000000000000007e+00;
  /* #99: @26 = (@3*@24) */
  for (i=0, rr=w26, cs=w24; i<3; ++i) (*rr++)  = (w3*(*cs++));
  /* #100: @25 = (@25-@26) */
  for (i=0, rr=w25, cs=w26; i<3; ++i) (*rr++) -= (*cs++);
  /* #101: @3 = 0.5 */
  w3 = 5.0000000000000000e-01;
  /* #102: @29 = zeros(4x1) */
  casadi_clear(w29, 4);
  /* #103: @21 = (-@7) */
  w21 = (- w7 );
  /* #104: @22 = (-@8) */
  w22 = (- w8 );
  /* #105: @23 = (-@9) */
  w23 = (- w9 );
  /* #106: @30 = horzcat(@6, @21, @22, @23) */
  rr=w30;
  *rr++ = w6;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  /* #107: @30 = @30' */
  /* #108: @21 = (-@9) */
  w21 = (- w9 );
  /* #109: @31 = horzcat(@7, @6, @21, @8) */
  rr=w31;
  *rr++ = w7;
  *rr++ = w6;
  *rr++ = w21;
  *rr++ = w8;
  /* #110: @31 = @31' */
  /* #111: @21 = (-@7) */
  w21 = (- w7 );
  /* #112: @32 = horzcat(@8, @9, @6, @21) */
  rr=w32;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w6;
  *rr++ = w21;
  /* #113: @32 = @32' */
  /* #114: @21 = (-@8) */
  w21 = (- w8 );
  /* #115: @33 = horzcat(@9, @21, @7, @6) */
  rr=w33;
  *rr++ = w9;
  *rr++ = w21;
  *rr++ = w7;
  *rr++ = w6;
  /* #116: @33 = @33' */
  /* #117: @34 = horzcat(@30, @31, @32, @33) */
  rr=w34;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w32; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<4; ++i) *rr++ = *cs++;
  /* #118: @35 = @34' */
  for (i=0, rr=w35, cs=w34; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #119: @21 = 0 */
  w21 = 0.;
  /* #120: @30 = vertcat(@21, @10, @11, @12) */
  rr=w30;
  *rr++ = w21;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #121: @29 = mac(@35,@30,@29) */
  for (i=0, rr=w29; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w35+j, tt=w30+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #122: @29 = (@3*@29) */
  for (i=0, rr=w29, cs=w29; i<4; ++i) (*rr++)  = (w3*(*cs++));
  /* #123: @21 = 10 */
  w21 = 10.;
  /* #124: @22 = 1 */
  w22 = 1.;
  /* #125: @23 = sq(@6) */
  w23 = casadi_sq( w6 );
  /* #126: @36 = sq(@7) */
  w36 = casadi_sq( w7 );
  /* #127: @23 = (@23+@36) */
  w23 += w36;
  /* #128: @36 = sq(@8) */
  w36 = casadi_sq( w8 );
  /* #129: @23 = (@23+@36) */
  w23 += w36;
  /* #130: @36 = sq(@9) */
  w36 = casadi_sq( w9 );
  /* #131: @23 = (@23+@36) */
  w23 += w36;
  /* #132: @22 = (@22-@23) */
  w22 -= w23;
  /* #133: @22 = (@21*@22) */
  w22  = (w21*w22);
  /* #134: @31 = (@22*@17) */
  for (i=0, rr=w31, cs=w17; i<4; ++i) (*rr++)  = (w22*(*cs++));
  /* #135: @29 = (@29+@31) */
  for (i=0, rr=w29, cs=w31; i<4; ++i) (*rr++) += (*cs++);
  /* #136: @26 = zeros(3x1) */
  casadi_clear(w26, 3);
  /* #137: @28 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w28);
  /* #138: @27 = zeros(3x3) */
  casadi_clear(w27, 9);
  /* #139: @23 = 0.00264 */
  w23 = 2.6400000000000000e-03;
  /* #140: (@27[0] = @23) */
  for (rr=w27+0, ss=(&w23); rr!=w27+1; rr+=1) *rr = *ss++;
  /* #141: @23 = 0.00264 */
  w23 = 2.6400000000000000e-03;
  /* #142: (@27[4] = @23) */
  for (rr=w27+4, ss=(&w23); rr!=w27+5; rr+=1) *rr = *ss++;
  /* #143: @23 = 0.00496 */
  w23 = 4.9600000000000000e-03;
  /* #144: (@27[8] = @23) */
  for (rr=w27+8, ss=(&w23); rr!=w27+9; rr+=1) *rr = *ss++;
  /* #145: @28 = (@27\@28) */
  rr = w28;
  ss = w27;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[6], r[6], beta[3], w[6];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 3, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #146: @23 = input[2][1] */
  w23 = arg[2] ? arg[2][1] : 0;
  /* #147: @36 = input[2][2] */
  w36 = arg[2] ? arg[2][2] : 0;
  /* #148: @37 = input[2][3] */
  w37 = arg[2] ? arg[2][3] : 0;
  /* #149: @31 = vertcat(@0, @23, @36, @37) */
  rr=w31;
  *rr++ = w0;
  *rr++ = w23;
  *rr++ = w36;
  *rr++ = w37;
  /* #150: @38 = @31[1:4] */
  for (rr=w38, ss=w31+1; ss!=w31+4; ss+=1) *rr++ = *ss;
  /* #151: @39 = zeros(3x1) */
  casadi_clear(w39, 3);
  /* #152: @40 = @14[10:13] */
  for (rr=w40, ss=w14+10; ss!=w14+13; ss+=1) *rr++ = *ss;
  /* #153: @39 = mac(@27,@40,@39) */
  for (i=0, rr=w39; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w27+j, tt=w40+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #154: @23 = @39[2] */
  for (rr=(&w23), ss=w39+2; ss!=w39+3; ss+=1) *rr++ = *ss;
  /* #155: @36 = (@11*@23) */
  w36  = (w11*w23);
  /* #156: @37 = @39[1] */
  for (rr=(&w37), ss=w39+1; ss!=w39+2; ss+=1) *rr++ = *ss;
  /* #157: @41 = (@12*@37) */
  w41  = (w12*w37);
  /* #158: @36 = (@36-@41) */
  w36 -= w41;
  /* #159: @41 = @39[0] */
  for (rr=(&w41), ss=w39+0; ss!=w39+1; ss+=1) *rr++ = *ss;
  /* #160: @42 = (@12*@41) */
  w42  = (w12*w41);
  /* #161: @43 = (@10*@23) */
  w43  = (w10*w23);
  /* #162: @42 = (@42-@43) */
  w42 -= w43;
  /* #163: @43 = (@10*@37) */
  w43  = (w10*w37);
  /* #164: @44 = (@11*@41) */
  w44  = (w11*w41);
  /* #165: @43 = (@43-@44) */
  w43 -= w44;
  /* #166: @39 = vertcat(@36, @42, @43) */
  rr=w39;
  *rr++ = w36;
  *rr++ = w42;
  *rr++ = w43;
  /* #167: @38 = (@38-@39) */
  for (i=0, rr=w38, cs=w39; i<3; ++i) (*rr++) -= (*cs++);
  /* #168: @26 = mac(@28,@38,@26) */
  for (i=0, rr=w26; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w28+j, tt=w38+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #169: @14 = vertcat(@15, @25, @29, @26) */
  rr=w14;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<3; ++i) *rr++ = *cs++;
  /* #170: @13 = (@13-@14) */
  for (i=0, rr=w13, cs=w14; i<13; ++i) (*rr++) -= (*cs++);
  /* #171: output[0][0] = @13 */
  casadi_copy(w13, 13, res[0]);
  /* #172: @45 = zeros(13x13,52nz) */
  casadi_clear(w45, 52);
  /* #173: @46 = ones(13x1,7nz) */
  casadi_fill(w46, 7, 1.);
  /* #174: {@36, @42, @43, @44, @47, @48, @49, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@46) */
  w36 = w46[0];
  w42 = w46[1];
  w43 = w46[2];
  w44 = w46[3];
  w47 = w46[4];
  w48 = w46[5];
  w49 = w46[6];
  /* #175: @50 = 00 */
  /* #176: @51 = 00 */
  /* #177: @52 = 00 */
  /* #178: @53 = 00 */
  /* #179: @54 = 00 */
  /* #180: @55 = 00 */
  /* #181: @46 = vertcat(@36, @42, @43, @44, @47, @48, @49, @50, @51, @52, @53, @54, @55) */
  rr=w46;
  *rr++ = w36;
  *rr++ = w42;
  *rr++ = w43;
  *rr++ = w44;
  *rr++ = w47;
  *rr++ = w48;
  *rr++ = w49;
  /* #182: @15 = @46[3:6] */
  for (rr=w15, ss=w46+3; ss!=w46+6; ss+=1) *rr++ = *ss;
  /* #183: @25 = zeros(3x1) */
  casadi_clear(w25, 3);
  /* #184: @36 = (2.*@2) */
  w36 = (2.* w2 );
  /* #185: @42 = sparsity_cast(@49) */
  casadi_copy((&w49), 1, (&w42));
  /* #186: @43 = (@42/@1) */
  w43  = (w42/w1);
  /* #187: @29 = dense(@43) */
  casadi_densify((&w43), casadi_s4, w29, 0);
  /* #188: @19 = (@19/@1) */
  for (i=0, rr=w19; i<4; ++i) (*rr++) /= w1;
  /* #189: @43 = 0 */
  w43 = 0.;
  /* #190: @43 = mac(@18,@42,@43) */
  casadi_mtimes(w18, casadi_s6, (&w42), casadi_s4, (&w43), casadi_s5, w, 0);
  /* #191: @44 = 0 */
  w44 = 0.;
  /* #192: @47 = @42' */
  casadi_copy((&w42), 1, (&w47));
  /* #193: @44 = mac(@47,@17,@44) */
  casadi_mtimes((&w47), casadi_s8, w17, casadi_s7, (&w44), casadi_s5, w, 0);
  /* #194: @43 = (@43+@44) */
  w43 += w44;
  /* #195: @31 = (@19*@43) */
  for (i=0, rr=w31, cr=w19; i<4; ++i) (*rr++)  = ((*cr++)*w43);
  /* #196: @29 = (@29-@31) */
  for (i=0, rr=w29, cs=w31; i<4; ++i) (*rr++) -= (*cs++);
  /* #197: @43 = @29[0] */
  for (rr=(&w43), ss=w29+0; ss!=w29+1; ss+=1) *rr++ = *ss;
  /* #198: @44 = (@36*@43) */
  w44  = (w36*w43);
  /* #199: @47 = (2.*@4) */
  w47 = (2.* w4 );
  /* #200: @48 = @29[1] */
  for (rr=(&w48), ss=w29+1; ss!=w29+2; ss+=1) *rr++ = *ss;
  /* #201: @56 = (@47*@48) */
  w56  = (w47*w48);
  /* #202: @44 = (@44+@56) */
  w44 += w56;
  /* #203: @56 = (2.*@5) */
  w56 = (2.* w5 );
  /* #204: @57 = @29[2] */
  for (rr=(&w57), ss=w29+2; ss!=w29+3; ss+=1) *rr++ = *ss;
  /* #205: @58 = (@56*@57) */
  w58  = (w56*w57);
  /* #206: @44 = (@44-@58) */
  w44 -= w58;
  /* #207: @58 = (2.*@20) */
  w58 = (2.* w20 );
  /* #208: @59 = @29[3] */
  for (rr=(&w59), ss=w29+3; ss!=w29+4; ss+=1) *rr++ = *ss;
  /* #209: @60 = (@58*@59) */
  w60  = (w58*w59);
  /* #210: @44 = (@44-@60) */
  w44 -= w60;
  /* #211: @60 = (@5*@48) */
  w60  = (w5*w48);
  /* #212: @61 = (@4*@57) */
  w61  = (w4*w57);
  /* #213: @60 = (@60+@61) */
  w60 += w61;
  /* #214: @61 = (@20*@43) */
  w61  = (w20*w43);
  /* #215: @62 = (@2*@59) */
  w62  = (w2*w59);
  /* #216: @61 = (@61+@62) */
  w61 += w62;
  /* #217: @60 = (@60-@61) */
  w60 -= w61;
  /* #218: @60 = (2.*@60) */
  w60 = (2.* w60 );
  /* #219: @61 = (@20*@48) */
  w61  = (w20*w48);
  /* #220: @62 = (@4*@59) */
  w62  = (w4*w59);
  /* #221: @61 = (@61+@62) */
  w61 += w62;
  /* #222: @62 = (@5*@43) */
  w62  = (w5*w43);
  /* #223: @63 = (@2*@57) */
  w63  = (w2*w57);
  /* #224: @62 = (@62+@63) */
  w62 += w63;
  /* #225: @61 = (@61+@62) */
  w61 += w62;
  /* #226: @61 = (2.*@61) */
  w61 = (2.* w61 );
  /* #227: @26 = horzcat(@44, @60, @61) */
  rr=w26;
  *rr++ = w44;
  *rr++ = w60;
  *rr++ = w61;
  /* #228: @26 = @26' */
  /* #229: @44 = (@5*@48) */
  w44  = (w5*w48);
  /* #230: @60 = (@4*@57) */
  w60  = (w4*w57);
  /* #231: @44 = (@44+@60) */
  w44 += w60;
  /* #232: @60 = (@20*@43) */
  w60  = (w20*w43);
  /* #233: @61 = (@2*@59) */
  w61  = (w2*w59);
  /* #234: @60 = (@60+@61) */
  w60 += w61;
  /* #235: @44 = (@44+@60) */
  w44 += w60;
  /* #236: @44 = (2.*@44) */
  w44 = (2.* w44 );
  /* #237: @60 = (2.*@2) */
  w60 = (2.* w2 );
  /* #238: @61 = (@60*@43) */
  w61  = (w60*w43);
  /* #239: @62 = (2.*@5) */
  w62 = (2.* w5 );
  /* #240: @63 = (@62*@57) */
  w63  = (w62*w57);
  /* #241: @61 = (@61+@63) */
  w61 += w63;
  /* #242: @63 = (2.*@4) */
  w63 = (2.* w4 );
  /* #243: @64 = (@63*@48) */
  w64  = (w63*w48);
  /* #244: @61 = (@61-@64) */
  w61 -= w64;
  /* #245: @64 = (2.*@20) */
  w64 = (2.* w20 );
  /* #246: @65 = (@64*@59) */
  w65  = (w64*w59);
  /* #247: @61 = (@61-@65) */
  w61 -= w65;
  /* #248: @65 = (@20*@57) */
  w65  = (w20*w57);
  /* #249: @66 = (@5*@59) */
  w66  = (w5*w59);
  /* #250: @65 = (@65+@66) */
  w65 += w66;
  /* #251: @66 = (@4*@43) */
  w66  = (w4*w43);
  /* #252: @67 = (@2*@48) */
  w67  = (w2*w48);
  /* #253: @66 = (@66+@67) */
  w66 += w67;
  /* #254: @65 = (@65-@66) */
  w65 -= w66;
  /* #255: @65 = (2.*@65) */
  w65 = (2.* w65 );
  /* #256: @38 = horzcat(@44, @61, @65) */
  rr=w38;
  *rr++ = w44;
  *rr++ = w61;
  *rr++ = w65;
  /* #257: @38 = @38' */
  /* #258: @44 = (@20*@48) */
  w44  = (w20*w48);
  /* #259: @61 = (@4*@59) */
  w61  = (w4*w59);
  /* #260: @44 = (@44+@61) */
  w44 += w61;
  /* #261: @61 = (@5*@43) */
  w61  = (w5*w43);
  /* #262: @65 = (@2*@57) */
  w65  = (w2*w57);
  /* #263: @61 = (@61+@65) */
  w61 += w65;
  /* #264: @44 = (@44-@61) */
  w44 -= w61;
  /* #265: @44 = (2.*@44) */
  w44 = (2.* w44 );
  /* #266: @61 = (@20*@57) */
  w61  = (w20*w57);
  /* #267: @65 = (@5*@59) */
  w65  = (w5*w59);
  /* #268: @61 = (@61+@65) */
  w61 += w65;
  /* #269: @65 = (@4*@43) */
  w65  = (w4*w43);
  /* #270: @66 = (@2*@48) */
  w66  = (w2*w48);
  /* #271: @65 = (@65+@66) */
  w65 += w66;
  /* #272: @61 = (@61+@65) */
  w61 += w65;
  /* #273: @61 = (2.*@61) */
  w61 = (2.* w61 );
  /* #274: @65 = (2.*@2) */
  w65 = (2.* w2 );
  /* #275: @43 = (@65*@43) */
  w43  = (w65*w43);
  /* #276: @66 = (2.*@20) */
  w66 = (2.* w20 );
  /* #277: @59 = (@66*@59) */
  w59  = (w66*w59);
  /* #278: @43 = (@43+@59) */
  w43 += w59;
  /* #279: @59 = (2.*@4) */
  w59 = (2.* w4 );
  /* #280: @48 = (@59*@48) */
  w48  = (w59*w48);
  /* #281: @43 = (@43-@48) */
  w43 -= w48;
  /* #282: @48 = (2.*@5) */
  w48 = (2.* w5 );
  /* #283: @57 = (@48*@57) */
  w57  = (w48*w57);
  /* #284: @43 = (@43-@57) */
  w43 -= w57;
  /* #285: @39 = horzcat(@44, @61, @43) */
  rr=w39;
  *rr++ = w44;
  *rr++ = w61;
  *rr++ = w43;
  /* #286: @39 = @39' */
  /* #287: @68 = horzcat(@26, @38, @39) */
  rr=w68;
  for (i=0, cs=w26; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w39; i<3; ++i) *rr++ = *cs++;
  /* #288: @69 = @68' */
  for (i=0, rr=w69, cs=w68; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #289: @25 = mac(@69,@24,@25) */
  for (i=0, rr=w25; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w69+j, tt=w24+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #290: @25 = (@0*@25) */
  for (i=0, rr=w25, cs=w25; i<3; ++i) (*rr++)  = (w0*(*cs++));
  /* #291: @53 = 00 */
  /* #292: @54 = 00 */
  /* #293: @55 = 00 */
  /* #294: @44 = horzcat(@49, @53, @54, @55) */
  rr=(&w44);
  *rr++ = w49;
  /* #295: @44 = @44' */
  /* #296: @53 = 00 */
  /* #297: @61 = horzcat(@50, @49, @53, @51) */
  rr=(&w61);
  *rr++ = w49;
  /* #298: @61 = @61' */
  /* #299: @53 = 00 */
  /* #300: @43 = horzcat(@51, @52, @49, @53) */
  rr=(&w43);
  *rr++ = w49;
  /* #301: @43 = @43' */
  /* #302: @51 = 00 */
  /* #303: @57 = horzcat(@52, @51, @50, @49) */
  rr=(&w57);
  *rr++ = w49;
  /* #304: @57 = @57' */
  /* #305: @29 = horzcat(@44, @61, @43, @57) */
  rr=w29;
  *rr++ = w44;
  *rr++ = w61;
  *rr++ = w43;
  *rr++ = w57;
  /* #306: @31 = @29' */
  casadi_trans(w29,casadi_s9, w31, casadi_s9, iw);
  /* #307: @31 = nonzeros(@31) */
  /* #308: @31 = (@31*@30) */
  for (i=0, rr=w31, cs=w30; i<4; ++i) (*rr++) *= (*cs++);
  /* #309: @31 = (@3*@31) */
  for (i=0, rr=w31, cs=w31; i<4; ++i) (*rr++)  = (w3*(*cs++));
  /* #310: @42 = (@22*@42) */
  w42  = (w22*w42);
  /* #311: @29 = dense(@42) */
  casadi_densify((&w42), casadi_s4, w29, 0);
  /* #312: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #313: @6 = (@6*@49) */
  w6 *= w49;
  /* #314: @6 = (@21*@6) */
  w6  = (w21*w6);
  /* #315: @32 = (@17*@6) */
  for (i=0, rr=w32, cr=w17; i<4; ++i) (*rr++)  = ((*cr++)*w6);
  /* #316: @29 = (@29-@32) */
  for (i=0, rr=w29, cs=w32; i<4; ++i) (*rr++) -= (*cs++);
  /* #317: @31 = (@31+@29) */
  for (i=0, rr=w31, cs=w29; i<4; ++i) (*rr++) += (*cs++);
  /* #318: @52 = zeros(3x1,0nz) */
  /* #319: @70 = vertcat(@15, @25, @31, @52) */
  rr=w70;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<4; ++i) *rr++ = *cs++;
  /* #320: @70 = (-@70) */
  for (i=0, rr=w70, cs=w70; i<10; ++i) *rr++ = (- *cs++ );
  /* #321: @71 = @70[:10] */
  for (rr=w71, ss=w70+0; ss!=w70+10; ss+=1) *rr++ = *ss;
  /* #322: (@45[0, 1, 2, 3, 7, 11, 15, 22, 29, 36] = @71) */
  for (cii=casadi_s10, rr=w45, ss=w71; cii!=casadi_s10+10; ++cii, ++ss) rr[*cii] = *ss;
  /* #323: @52 = zeros(3x1,0nz) */
  /* #324: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #325: @6 = ones(13x1,1nz) */
  w6 = 1.;
  /* #326: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, @49, NULL, NULL, NULL, NULL, NULL} = vertsplit(@6) */
  w49 = w6;
  /* #327: @6 = sparsity_cast(@49) */
  casadi_copy((&w49), 1, (&w6));
  /* #328: @42 = (@6/@1) */
  w42  = (w6/w1);
  /* #329: @31 = dense(@42) */
  casadi_densify((&w42), casadi_s11, w31, 0);
  /* #330: @42 = 0 */
  w42 = 0.;
  /* #331: @42 = mac(@18,@6,@42) */
  casadi_mtimes(w18, casadi_s6, (&w6), casadi_s11, (&w42), casadi_s5, w, 0);
  /* #332: @44 = 0 */
  w44 = 0.;
  /* #333: @61 = @6' */
  casadi_copy((&w6), 1, (&w61));
  /* #334: @44 = mac(@61,@17,@44) */
  casadi_mtimes((&w61), casadi_s12, w17, casadi_s7, (&w44), casadi_s5, w, 0);
  /* #335: @42 = (@42+@44) */
  w42 += w44;
  /* #336: @29 = (@19*@42) */
  for (i=0, rr=w29, cr=w19; i<4; ++i) (*rr++)  = ((*cr++)*w42);
  /* #337: @31 = (@31-@29) */
  for (i=0, rr=w31, cs=w29; i<4; ++i) (*rr++) -= (*cs++);
  /* #338: @42 = @31[0] */
  for (rr=(&w42), ss=w31+0; ss!=w31+1; ss+=1) *rr++ = *ss;
  /* #339: @44 = (@36*@42) */
  w44  = (w36*w42);
  /* #340: @61 = @31[1] */
  for (rr=(&w61), ss=w31+1; ss!=w31+2; ss+=1) *rr++ = *ss;
  /* #341: @43 = (@47*@61) */
  w43  = (w47*w61);
  /* #342: @44 = (@44+@43) */
  w44 += w43;
  /* #343: @43 = @31[2] */
  for (rr=(&w43), ss=w31+2; ss!=w31+3; ss+=1) *rr++ = *ss;
  /* #344: @57 = (@56*@43) */
  w57  = (w56*w43);
  /* #345: @44 = (@44-@57) */
  w44 -= w57;
  /* #346: @57 = @31[3] */
  for (rr=(&w57), ss=w31+3; ss!=w31+4; ss+=1) *rr++ = *ss;
  /* #347: @67 = (@58*@57) */
  w67  = (w58*w57);
  /* #348: @44 = (@44-@67) */
  w44 -= w67;
  /* #349: @67 = (@5*@61) */
  w67  = (w5*w61);
  /* #350: @72 = (@4*@43) */
  w72  = (w4*w43);
  /* #351: @67 = (@67+@72) */
  w67 += w72;
  /* #352: @72 = (@20*@42) */
  w72  = (w20*w42);
  /* #353: @73 = (@2*@57) */
  w73  = (w2*w57);
  /* #354: @72 = (@72+@73) */
  w72 += w73;
  /* #355: @67 = (@67-@72) */
  w67 -= w72;
  /* #356: @67 = (2.*@67) */
  w67 = (2.* w67 );
  /* #357: @72 = (@20*@61) */
  w72  = (w20*w61);
  /* #358: @73 = (@4*@57) */
  w73  = (w4*w57);
  /* #359: @72 = (@72+@73) */
  w72 += w73;
  /* #360: @73 = (@5*@42) */
  w73  = (w5*w42);
  /* #361: @74 = (@2*@43) */
  w74  = (w2*w43);
  /* #362: @73 = (@73+@74) */
  w73 += w74;
  /* #363: @72 = (@72+@73) */
  w72 += w73;
  /* #364: @72 = (2.*@72) */
  w72 = (2.* w72 );
  /* #365: @25 = horzcat(@44, @67, @72) */
  rr=w25;
  *rr++ = w44;
  *rr++ = w67;
  *rr++ = w72;
  /* #366: @25 = @25' */
  /* #367: @44 = (@5*@61) */
  w44  = (w5*w61);
  /* #368: @67 = (@4*@43) */
  w67  = (w4*w43);
  /* #369: @44 = (@44+@67) */
  w44 += w67;
  /* #370: @67 = (@20*@42) */
  w67  = (w20*w42);
  /* #371: @72 = (@2*@57) */
  w72  = (w2*w57);
  /* #372: @67 = (@67+@72) */
  w67 += w72;
  /* #373: @44 = (@44+@67) */
  w44 += w67;
  /* #374: @44 = (2.*@44) */
  w44 = (2.* w44 );
  /* #375: @67 = (@60*@42) */
  w67  = (w60*w42);
  /* #376: @72 = (@62*@43) */
  w72  = (w62*w43);
  /* #377: @67 = (@67+@72) */
  w67 += w72;
  /* #378: @72 = (@63*@61) */
  w72  = (w63*w61);
  /* #379: @67 = (@67-@72) */
  w67 -= w72;
  /* #380: @72 = (@64*@57) */
  w72  = (w64*w57);
  /* #381: @67 = (@67-@72) */
  w67 -= w72;
  /* #382: @72 = (@20*@43) */
  w72  = (w20*w43);
  /* #383: @73 = (@5*@57) */
  w73  = (w5*w57);
  /* #384: @72 = (@72+@73) */
  w72 += w73;
  /* #385: @73 = (@4*@42) */
  w73  = (w4*w42);
  /* #386: @74 = (@2*@61) */
  w74  = (w2*w61);
  /* #387: @73 = (@73+@74) */
  w73 += w74;
  /* #388: @72 = (@72-@73) */
  w72 -= w73;
  /* #389: @72 = (2.*@72) */
  w72 = (2.* w72 );
  /* #390: @26 = horzcat(@44, @67, @72) */
  rr=w26;
  *rr++ = w44;
  *rr++ = w67;
  *rr++ = w72;
  /* #391: @26 = @26' */
  /* #392: @44 = (@20*@61) */
  w44  = (w20*w61);
  /* #393: @67 = (@4*@57) */
  w67  = (w4*w57);
  /* #394: @44 = (@44+@67) */
  w44 += w67;
  /* #395: @67 = (@5*@42) */
  w67  = (w5*w42);
  /* #396: @72 = (@2*@43) */
  w72  = (w2*w43);
  /* #397: @67 = (@67+@72) */
  w67 += w72;
  /* #398: @44 = (@44-@67) */
  w44 -= w67;
  /* #399: @44 = (2.*@44) */
  w44 = (2.* w44 );
  /* #400: @67 = (@20*@43) */
  w67  = (w20*w43);
  /* #401: @72 = (@5*@57) */
  w72  = (w5*w57);
  /* #402: @67 = (@67+@72) */
  w67 += w72;
  /* #403: @72 = (@4*@42) */
  w72  = (w4*w42);
  /* #404: @73 = (@2*@61) */
  w73  = (w2*w61);
  /* #405: @72 = (@72+@73) */
  w72 += w73;
  /* #406: @67 = (@67+@72) */
  w67 += w72;
  /* #407: @67 = (2.*@67) */
  w67 = (2.* w67 );
  /* #408: @42 = (@65*@42) */
  w42  = (w65*w42);
  /* #409: @57 = (@66*@57) */
  w57  = (w66*w57);
  /* #410: @42 = (@42+@57) */
  w42 += w57;
  /* #411: @61 = (@59*@61) */
  w61  = (w59*w61);
  /* #412: @42 = (@42-@61) */
  w42 -= w61;
  /* #413: @43 = (@48*@43) */
  w43  = (w48*w43);
  /* #414: @42 = (@42-@43) */
  w42 -= w43;
  /* #415: @38 = horzcat(@44, @67, @42) */
  rr=w38;
  *rr++ = w44;
  *rr++ = w67;
  *rr++ = w42;
  /* #416: @38 = @38' */
  /* #417: @69 = horzcat(@25, @26, @38) */
  rr=w69;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<3; ++i) *rr++ = *cs++;
  /* #418: @68 = @69' */
  for (i=0, rr=w68, cs=w69; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #419: @15 = mac(@68,@24,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w68+j, tt=w24+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #420: @15 = (@0*@15) */
  for (i=0, rr=w15, cs=w15; i<3; ++i) (*rr++)  = (w0*(*cs++));
  /* #421: @51 = 00 */
  /* #422: @44 = (-@49) */
  w44 = (- w49 );
  /* #423: @50 = 00 */
  /* #424: @53 = 00 */
  /* #425: @67 = horzcat(@51, @44, @50, @53) */
  rr=(&w67);
  *rr++ = w44;
  /* #426: @67 = @67' */
  /* #427: @50 = 00 */
  /* #428: @53 = 00 */
  /* #429: @44 = horzcat(@49, @51, @50, @53) */
  rr=(&w44);
  *rr++ = w49;
  /* #430: @44 = @44' */
  /* #431: @50 = 00 */
  /* #432: @42 = (-@49) */
  w42 = (- w49 );
  /* #433: @43 = horzcat(@53, @50, @51, @42) */
  rr=(&w43);
  *rr++ = w42;
  /* #434: @43 = @43' */
  /* #435: @53 = 00 */
  /* #436: @42 = horzcat(@50, @53, @49, @51) */
  rr=(&w42);
  *rr++ = w49;
  /* #437: @42 = @42' */
  /* #438: @31 = horzcat(@67, @44, @43, @42) */
  rr=w31;
  *rr++ = w67;
  *rr++ = w44;
  *rr++ = w43;
  *rr++ = w42;
  /* #439: @29 = @31' */
  casadi_trans(w31,casadi_s13, w29, casadi_s13, iw);
  /* #440: @29 = nonzeros(@29) */
  /* #441: @29 = (@29*@30) */
  for (i=0, rr=w29, cs=w30; i<4; ++i) (*rr++) *= (*cs++);
  /* #442: @31 = @29[1, 0, 3, 2] */
  for (cii=casadi_s14, rr=w31, ss=w29; cii!=casadi_s14+4; ++cii) *rr++ = ss[*cii];
  /* #443: @31 = (@3*@31) */
  for (i=0, rr=w31, cs=w31; i<4; ++i) (*rr++)  = (w3*(*cs++));
  /* #444: @6 = (@22*@6) */
  w6  = (w22*w6);
  /* #445: @29 = dense(@6) */
  casadi_densify((&w6), casadi_s11, w29, 0);
  /* #446: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #447: @7 = (@7*@49) */
  w7 *= w49;
  /* #448: @7 = (@21*@7) */
  w7  = (w21*w7);
  /* #449: @32 = (@17*@7) */
  for (i=0, rr=w32, cr=w17; i<4; ++i) (*rr++)  = ((*cr++)*w7);
  /* #450: @29 = (@29-@32) */
  for (i=0, rr=w29, cs=w32; i<4; ++i) (*rr++) -= (*cs++);
  /* #451: @31 = (@31+@29) */
  for (i=0, rr=w31, cs=w29; i<4; ++i) (*rr++) += (*cs++);
  /* #452: @50 = zeros(3x1,0nz) */
  /* #453: @46 = vertcat(@52, @15, @31, @50) */
  rr=w46;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<4; ++i) *rr++ = *cs++;
  /* #454: @46 = (-@46) */
  for (i=0, rr=w46, cs=w46; i<7; ++i) *rr++ = (- *cs++ );
  /* #455: @75 = @46[:7] */
  for (rr=w75, ss=w46+0; ss!=w46+7; ss+=1) *rr++ = *ss;
  /* #456: (@45[4, 8, 12, 16, 23, 30, 37] = @75) */
  for (cii=casadi_s15, rr=w45, ss=w75; cii!=casadi_s15+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #457: @52 = zeros(3x1,0nz) */
  /* #458: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #459: @7 = ones(13x1,1nz) */
  w7 = 1.;
  /* #460: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @49, NULL, NULL, NULL, NULL} = vertsplit(@7) */
  w49 = w7;
  /* #461: @7 = sparsity_cast(@49) */
  casadi_copy((&w49), 1, (&w7));
  /* #462: @6 = (@7/@1) */
  w6  = (w7/w1);
  /* #463: @31 = dense(@6) */
  casadi_densify((&w6), casadi_s16, w31, 0);
  /* #464: @6 = 0 */
  w6 = 0.;
  /* #465: @6 = mac(@18,@7,@6) */
  casadi_mtimes(w18, casadi_s6, (&w7), casadi_s16, (&w6), casadi_s5, w, 0);
  /* #466: @67 = 0 */
  w67 = 0.;
  /* #467: @44 = @7' */
  casadi_copy((&w7), 1, (&w44));
  /* #468: @67 = mac(@44,@17,@67) */
  casadi_mtimes((&w44), casadi_s17, w17, casadi_s7, (&w67), casadi_s5, w, 0);
  /* #469: @6 = (@6+@67) */
  w6 += w67;
  /* #470: @29 = (@19*@6) */
  for (i=0, rr=w29, cr=w19; i<4; ++i) (*rr++)  = ((*cr++)*w6);
  /* #471: @31 = (@31-@29) */
  for (i=0, rr=w31, cs=w29; i<4; ++i) (*rr++) -= (*cs++);
  /* #472: @6 = @31[0] */
  for (rr=(&w6), ss=w31+0; ss!=w31+1; ss+=1) *rr++ = *ss;
  /* #473: @67 = (@36*@6) */
  w67  = (w36*w6);
  /* #474: @44 = @31[1] */
  for (rr=(&w44), ss=w31+1; ss!=w31+2; ss+=1) *rr++ = *ss;
  /* #475: @43 = (@47*@44) */
  w43  = (w47*w44);
  /* #476: @67 = (@67+@43) */
  w67 += w43;
  /* #477: @43 = @31[2] */
  for (rr=(&w43), ss=w31+2; ss!=w31+3; ss+=1) *rr++ = *ss;
  /* #478: @42 = (@56*@43) */
  w42  = (w56*w43);
  /* #479: @67 = (@67-@42) */
  w67 -= w42;
  /* #480: @42 = @31[3] */
  for (rr=(&w42), ss=w31+3; ss!=w31+4; ss+=1) *rr++ = *ss;
  /* #481: @61 = (@58*@42) */
  w61  = (w58*w42);
  /* #482: @67 = (@67-@61) */
  w67 -= w61;
  /* #483: @61 = (@5*@44) */
  w61  = (w5*w44);
  /* #484: @57 = (@4*@43) */
  w57  = (w4*w43);
  /* #485: @61 = (@61+@57) */
  w61 += w57;
  /* #486: @57 = (@20*@6) */
  w57  = (w20*w6);
  /* #487: @72 = (@2*@42) */
  w72  = (w2*w42);
  /* #488: @57 = (@57+@72) */
  w57 += w72;
  /* #489: @61 = (@61-@57) */
  w61 -= w57;
  /* #490: @61 = (2.*@61) */
  w61 = (2.* w61 );
  /* #491: @57 = (@20*@44) */
  w57  = (w20*w44);
  /* #492: @72 = (@4*@42) */
  w72  = (w4*w42);
  /* #493: @57 = (@57+@72) */
  w57 += w72;
  /* #494: @72 = (@5*@6) */
  w72  = (w5*w6);
  /* #495: @73 = (@2*@43) */
  w73  = (w2*w43);
  /* #496: @72 = (@72+@73) */
  w72 += w73;
  /* #497: @57 = (@57+@72) */
  w57 += w72;
  /* #498: @57 = (2.*@57) */
  w57 = (2.* w57 );
  /* #499: @25 = horzcat(@67, @61, @57) */
  rr=w25;
  *rr++ = w67;
  *rr++ = w61;
  *rr++ = w57;
  /* #500: @25 = @25' */
  /* #501: @67 = (@5*@44) */
  w67  = (w5*w44);
  /* #502: @61 = (@4*@43) */
  w61  = (w4*w43);
  /* #503: @67 = (@67+@61) */
  w67 += w61;
  /* #504: @61 = (@20*@6) */
  w61  = (w20*w6);
  /* #505: @57 = (@2*@42) */
  w57  = (w2*w42);
  /* #506: @61 = (@61+@57) */
  w61 += w57;
  /* #507: @67 = (@67+@61) */
  w67 += w61;
  /* #508: @67 = (2.*@67) */
  w67 = (2.* w67 );
  /* #509: @61 = (@60*@6) */
  w61  = (w60*w6);
  /* #510: @57 = (@62*@43) */
  w57  = (w62*w43);
  /* #511: @61 = (@61+@57) */
  w61 += w57;
  /* #512: @57 = (@63*@44) */
  w57  = (w63*w44);
  /* #513: @61 = (@61-@57) */
  w61 -= w57;
  /* #514: @57 = (@64*@42) */
  w57  = (w64*w42);
  /* #515: @61 = (@61-@57) */
  w61 -= w57;
  /* #516: @57 = (@20*@43) */
  w57  = (w20*w43);
  /* #517: @72 = (@5*@42) */
  w72  = (w5*w42);
  /* #518: @57 = (@57+@72) */
  w57 += w72;
  /* #519: @72 = (@4*@6) */
  w72  = (w4*w6);
  /* #520: @73 = (@2*@44) */
  w73  = (w2*w44);
  /* #521: @72 = (@72+@73) */
  w72 += w73;
  /* #522: @57 = (@57-@72) */
  w57 -= w72;
  /* #523: @57 = (2.*@57) */
  w57 = (2.* w57 );
  /* #524: @26 = horzcat(@67, @61, @57) */
  rr=w26;
  *rr++ = w67;
  *rr++ = w61;
  *rr++ = w57;
  /* #525: @26 = @26' */
  /* #526: @67 = (@20*@44) */
  w67  = (w20*w44);
  /* #527: @61 = (@4*@42) */
  w61  = (w4*w42);
  /* #528: @67 = (@67+@61) */
  w67 += w61;
  /* #529: @61 = (@5*@6) */
  w61  = (w5*w6);
  /* #530: @57 = (@2*@43) */
  w57  = (w2*w43);
  /* #531: @61 = (@61+@57) */
  w61 += w57;
  /* #532: @67 = (@67-@61) */
  w67 -= w61;
  /* #533: @67 = (2.*@67) */
  w67 = (2.* w67 );
  /* #534: @61 = (@20*@43) */
  w61  = (w20*w43);
  /* #535: @57 = (@5*@42) */
  w57  = (w5*w42);
  /* #536: @61 = (@61+@57) */
  w61 += w57;
  /* #537: @57 = (@4*@6) */
  w57  = (w4*w6);
  /* #538: @72 = (@2*@44) */
  w72  = (w2*w44);
  /* #539: @57 = (@57+@72) */
  w57 += w72;
  /* #540: @61 = (@61+@57) */
  w61 += w57;
  /* #541: @61 = (2.*@61) */
  w61 = (2.* w61 );
  /* #542: @6 = (@65*@6) */
  w6  = (w65*w6);
  /* #543: @42 = (@66*@42) */
  w42  = (w66*w42);
  /* #544: @6 = (@6+@42) */
  w6 += w42;
  /* #545: @44 = (@59*@44) */
  w44  = (w59*w44);
  /* #546: @6 = (@6-@44) */
  w6 -= w44;
  /* #547: @43 = (@48*@43) */
  w43  = (w48*w43);
  /* #548: @6 = (@6-@43) */
  w6 -= w43;
  /* #549: @38 = horzcat(@67, @61, @6) */
  rr=w38;
  *rr++ = w67;
  *rr++ = w61;
  *rr++ = w6;
  /* #550: @38 = @38' */
  /* #551: @68 = horzcat(@25, @26, @38) */
  rr=w68;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<3; ++i) *rr++ = *cs++;
  /* #552: @69 = @68' */
  for (i=0, rr=w69, cs=w68; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #553: @15 = mac(@69,@24,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w69+j, tt=w24+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #554: @15 = (@0*@15) */
  for (i=0, rr=w15, cs=w15; i<3; ++i) (*rr++)  = (w0*(*cs++));
  /* #555: @50 = 00 */
  /* #556: @53 = 00 */
  /* #557: @67 = (-@49) */
  w67 = (- w49 );
  /* #558: @51 = 00 */
  /* #559: @61 = horzcat(@50, @53, @67, @51) */
  rr=(&w61);
  *rr++ = w67;
  /* #560: @61 = @61' */
  /* #561: @53 = 00 */
  /* #562: @51 = 00 */
  /* #563: @67 = horzcat(@53, @50, @51, @49) */
  rr=(&w67);
  *rr++ = w49;
  /* #564: @67 = @67' */
  /* #565: @51 = 00 */
  /* #566: @54 = 00 */
  /* #567: @6 = horzcat(@49, @51, @50, @54) */
  rr=(&w6);
  *rr++ = w49;
  /* #568: @6 = @6' */
  /* #569: @43 = (-@49) */
  w43 = (- w49 );
  /* #570: @44 = horzcat(@51, @43, @53, @50) */
  rr=(&w44);
  *rr++ = w43;
  /* #571: @44 = @44' */
  /* #572: @31 = horzcat(@61, @67, @6, @44) */
  rr=w31;
  *rr++ = w61;
  *rr++ = w67;
  *rr++ = w6;
  *rr++ = w44;
  /* #573: @29 = @31' */
  casadi_trans(w31,casadi_s18, w29, casadi_s18, iw);
  /* #574: @29 = nonzeros(@29) */
  /* #575: @29 = (@29*@30) */
  for (i=0, rr=w29, cs=w30; i<4; ++i) (*rr++) *= (*cs++);
  /* #576: @31 = @29[2, 3, 0, 1] */
  for (cii=casadi_s19, rr=w31, ss=w29; cii!=casadi_s19+4; ++cii) *rr++ = ss[*cii];
  /* #577: @31 = (@3*@31) */
  for (i=0, rr=w31, cs=w31; i<4; ++i) (*rr++)  = (w3*(*cs++));
  /* #578: @7 = (@22*@7) */
  w7  = (w22*w7);
  /* #579: @29 = dense(@7) */
  casadi_densify((&w7), casadi_s16, w29, 0);
  /* #580: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #581: @8 = (@8*@49) */
  w8 *= w49;
  /* #582: @8 = (@21*@8) */
  w8  = (w21*w8);
  /* #583: @32 = (@17*@8) */
  for (i=0, rr=w32, cr=w17; i<4; ++i) (*rr++)  = ((*cr++)*w8);
  /* #584: @29 = (@29-@32) */
  for (i=0, rr=w29, cs=w32; i<4; ++i) (*rr++) -= (*cs++);
  /* #585: @31 = (@31+@29) */
  for (i=0, rr=w31, cs=w29; i<4; ++i) (*rr++) += (*cs++);
  /* #586: @51 = zeros(3x1,0nz) */
  /* #587: @75 = vertcat(@52, @15, @31, @51) */
  rr=w75;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<4; ++i) *rr++ = *cs++;
  /* #588: @75 = (-@75) */
  for (i=0, rr=w75, cs=w75; i<7; ++i) *rr++ = (- *cs++ );
  /* #589: @46 = @75[:7] */
  for (rr=w46, ss=w75+0; ss!=w75+7; ss+=1) *rr++ = *ss;
  /* #590: (@45[5, 9, 13, 17, 24, 31, 38] = @46) */
  for (cii=casadi_s20, rr=w45, ss=w46; cii!=casadi_s20+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #591: @52 = zeros(3x1,0nz) */
  /* #592: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #593: @8 = ones(13x1,1nz) */
  w8 = 1.;
  /* #594: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @49, NULL, NULL, NULL} = vertsplit(@8) */
  w49 = w8;
  /* #595: @8 = sparsity_cast(@49) */
  casadi_copy((&w49), 1, (&w8));
  /* #596: @1 = (@8/@1) */
  w1  = (w8/w1);
  /* #597: @31 = dense(@1) */
  casadi_densify((&w1), casadi_s21, w31, 0);
  /* #598: @1 = 0 */
  w1 = 0.;
  /* #599: @1 = mac(@18,@8,@1) */
  casadi_mtimes(w18, casadi_s6, (&w8), casadi_s21, (&w1), casadi_s5, w, 0);
  /* #600: @7 = 0 */
  w7 = 0.;
  /* #601: @61 = @8' */
  casadi_copy((&w8), 1, (&w61));
  /* #602: @7 = mac(@61,@17,@7) */
  casadi_mtimes((&w61), casadi_s22, w17, casadi_s7, (&w7), casadi_s5, w, 0);
  /* #603: @1 = (@1+@7) */
  w1 += w7;
  /* #604: @19 = (@19*@1) */
  for (i=0, rr=w19; i<4; ++i) (*rr++) *= w1;
  /* #605: @31 = (@31-@19) */
  for (i=0, rr=w31, cs=w19; i<4; ++i) (*rr++) -= (*cs++);
  /* #606: @1 = @31[0] */
  for (rr=(&w1), ss=w31+0; ss!=w31+1; ss+=1) *rr++ = *ss;
  /* #607: @36 = (@36*@1) */
  w36 *= w1;
  /* #608: @7 = @31[1] */
  for (rr=(&w7), ss=w31+1; ss!=w31+2; ss+=1) *rr++ = *ss;
  /* #609: @47 = (@47*@7) */
  w47 *= w7;
  /* #610: @36 = (@36+@47) */
  w36 += w47;
  /* #611: @47 = @31[2] */
  for (rr=(&w47), ss=w31+2; ss!=w31+3; ss+=1) *rr++ = *ss;
  /* #612: @56 = (@56*@47) */
  w56 *= w47;
  /* #613: @36 = (@36-@56) */
  w36 -= w56;
  /* #614: @56 = @31[3] */
  for (rr=(&w56), ss=w31+3; ss!=w31+4; ss+=1) *rr++ = *ss;
  /* #615: @58 = (@58*@56) */
  w58 *= w56;
  /* #616: @36 = (@36-@58) */
  w36 -= w58;
  /* #617: @58 = (@5*@7) */
  w58  = (w5*w7);
  /* #618: @61 = (@4*@47) */
  w61  = (w4*w47);
  /* #619: @58 = (@58+@61) */
  w58 += w61;
  /* #620: @61 = (@20*@1) */
  w61  = (w20*w1);
  /* #621: @67 = (@2*@56) */
  w67  = (w2*w56);
  /* #622: @61 = (@61+@67) */
  w61 += w67;
  /* #623: @58 = (@58-@61) */
  w58 -= w61;
  /* #624: @58 = (2.*@58) */
  w58 = (2.* w58 );
  /* #625: @61 = (@20*@7) */
  w61  = (w20*w7);
  /* #626: @67 = (@4*@56) */
  w67  = (w4*w56);
  /* #627: @61 = (@61+@67) */
  w61 += w67;
  /* #628: @67 = (@5*@1) */
  w67  = (w5*w1);
  /* #629: @6 = (@2*@47) */
  w6  = (w2*w47);
  /* #630: @67 = (@67+@6) */
  w67 += w6;
  /* #631: @61 = (@61+@67) */
  w61 += w67;
  /* #632: @61 = (2.*@61) */
  w61 = (2.* w61 );
  /* #633: @25 = horzcat(@36, @58, @61) */
  rr=w25;
  *rr++ = w36;
  *rr++ = w58;
  *rr++ = w61;
  /* #634: @25 = @25' */
  /* #635: @36 = (@5*@7) */
  w36  = (w5*w7);
  /* #636: @58 = (@4*@47) */
  w58  = (w4*w47);
  /* #637: @36 = (@36+@58) */
  w36 += w58;
  /* #638: @58 = (@20*@1) */
  w58  = (w20*w1);
  /* #639: @61 = (@2*@56) */
  w61  = (w2*w56);
  /* #640: @58 = (@58+@61) */
  w58 += w61;
  /* #641: @36 = (@36+@58) */
  w36 += w58;
  /* #642: @36 = (2.*@36) */
  w36 = (2.* w36 );
  /* #643: @60 = (@60*@1) */
  w60 *= w1;
  /* #644: @62 = (@62*@47) */
  w62 *= w47;
  /* #645: @60 = (@60+@62) */
  w60 += w62;
  /* #646: @63 = (@63*@7) */
  w63 *= w7;
  /* #647: @60 = (@60-@63) */
  w60 -= w63;
  /* #648: @64 = (@64*@56) */
  w64 *= w56;
  /* #649: @60 = (@60-@64) */
  w60 -= w64;
  /* #650: @64 = (@20*@47) */
  w64  = (w20*w47);
  /* #651: @63 = (@5*@56) */
  w63  = (w5*w56);
  /* #652: @64 = (@64+@63) */
  w64 += w63;
  /* #653: @63 = (@4*@1) */
  w63  = (w4*w1);
  /* #654: @62 = (@2*@7) */
  w62  = (w2*w7);
  /* #655: @63 = (@63+@62) */
  w63 += w62;
  /* #656: @64 = (@64-@63) */
  w64 -= w63;
  /* #657: @64 = (2.*@64) */
  w64 = (2.* w64 );
  /* #658: @26 = horzcat(@36, @60, @64) */
  rr=w26;
  *rr++ = w36;
  *rr++ = w60;
  *rr++ = w64;
  /* #659: @26 = @26' */
  /* #660: @36 = (@20*@7) */
  w36  = (w20*w7);
  /* #661: @60 = (@4*@56) */
  w60  = (w4*w56);
  /* #662: @36 = (@36+@60) */
  w36 += w60;
  /* #663: @60 = (@5*@1) */
  w60  = (w5*w1);
  /* #664: @64 = (@2*@47) */
  w64  = (w2*w47);
  /* #665: @60 = (@60+@64) */
  w60 += w64;
  /* #666: @36 = (@36-@60) */
  w36 -= w60;
  /* #667: @36 = (2.*@36) */
  w36 = (2.* w36 );
  /* #668: @20 = (@20*@47) */
  w20 *= w47;
  /* #669: @5 = (@5*@56) */
  w5 *= w56;
  /* #670: @20 = (@20+@5) */
  w20 += w5;
  /* #671: @4 = (@4*@1) */
  w4 *= w1;
  /* #672: @2 = (@2*@7) */
  w2 *= w7;
  /* #673: @4 = (@4+@2) */
  w4 += w2;
  /* #674: @20 = (@20+@4) */
  w20 += w4;
  /* #675: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #676: @65 = (@65*@1) */
  w65 *= w1;
  /* #677: @66 = (@66*@56) */
  w66 *= w56;
  /* #678: @65 = (@65+@66) */
  w65 += w66;
  /* #679: @59 = (@59*@7) */
  w59 *= w7;
  /* #680: @65 = (@65-@59) */
  w65 -= w59;
  /* #681: @48 = (@48*@47) */
  w48 *= w47;
  /* #682: @65 = (@65-@48) */
  w65 -= w48;
  /* #683: @38 = horzcat(@36, @20, @65) */
  rr=w38;
  *rr++ = w36;
  *rr++ = w20;
  *rr++ = w65;
  /* #684: @38 = @38' */
  /* #685: @69 = horzcat(@25, @26, @38) */
  rr=w69;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<3; ++i) *rr++ = *cs++;
  /* #686: @68 = @69' */
  for (i=0, rr=w68, cs=w69; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #687: @15 = mac(@68,@24,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w68+j, tt=w24+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #688: @15 = (@0*@15) */
  for (i=0, rr=w15, cs=w15; i<3; ++i) (*rr++)  = (w0*(*cs++));
  /* #689: @51 = 00 */
  /* #690: @53 = 00 */
  /* #691: @50 = 00 */
  /* #692: @0 = (-@49) */
  w0 = (- w49 );
  /* #693: @36 = horzcat(@51, @53, @50, @0) */
  rr=(&w36);
  *rr++ = w0;
  /* #694: @36 = @36' */
  /* #695: @53 = 00 */
  /* #696: @0 = (-@49) */
  w0 = (- w49 );
  /* #697: @50 = 00 */
  /* #698: @20 = horzcat(@53, @51, @0, @50) */
  rr=(&w20);
  *rr++ = w0;
  /* #699: @20 = @20' */
  /* #700: @54 = 00 */
  /* #701: @0 = horzcat(@50, @49, @51, @54) */
  rr=(&w0);
  *rr++ = w49;
  /* #702: @0 = @0' */
  /* #703: @50 = 00 */
  /* #704: @65 = horzcat(@49, @50, @53, @51) */
  rr=(&w65);
  *rr++ = w49;
  /* #705: @65 = @65' */
  /* #706: @31 = horzcat(@36, @20, @0, @65) */
  rr=w31;
  *rr++ = w36;
  *rr++ = w20;
  *rr++ = w0;
  *rr++ = w65;
  /* #707: @19 = @31' */
  casadi_trans(w31,casadi_s23, w19, casadi_s23, iw);
  /* #708: @19 = nonzeros(@19) */
  /* #709: @19 = (@19*@30) */
  for (i=0, rr=w19, cs=w30; i<4; ++i) (*rr++) *= (*cs++);
  /* #710: @30 = @19[3, 2, 1, 0] */
  for (cii=casadi_s24, rr=w30, ss=w19; cii!=casadi_s24+4; ++cii) *rr++ = ss[*cii];
  /* #711: @30 = (@3*@30) */
  for (i=0, rr=w30, cs=w30; i<4; ++i) (*rr++)  = (w3*(*cs++));
  /* #712: @22 = (@22*@8) */
  w22 *= w8;
  /* #713: @19 = dense(@22) */
  casadi_densify((&w22), casadi_s21, w19, 0);
  /* #714: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #715: @9 = (@9*@49) */
  w9 *= w49;
  /* #716: @21 = (@21*@9) */
  w21 *= w9;
  /* #717: @17 = (@17*@21) */
  for (i=0, rr=w17; i<4; ++i) (*rr++) *= w21;
  /* #718: @19 = (@19-@17) */
  for (i=0, rr=w19, cs=w17; i<4; ++i) (*rr++) -= (*cs++);
  /* #719: @30 = (@30+@19) */
  for (i=0, rr=w30, cs=w19; i<4; ++i) (*rr++) += (*cs++);
  /* #720: @50 = zeros(3x1,0nz) */
  /* #721: @46 = vertcat(@52, @15, @30, @50) */
  rr=w46;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  /* #722: @46 = (-@46) */
  for (i=0, rr=w46, cs=w46; i<7; ++i) *rr++ = (- *cs++ );
  /* #723: @75 = @46[:7] */
  for (rr=w75, ss=w46+0; ss!=w46+7; ss+=1) *rr++ = *ss;
  /* #724: (@45[6, 10, 14, 18, 25, 32, 39] = @75) */
  for (cii=casadi_s25, rr=w45, ss=w75; cii!=casadi_s25+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #725: @52 = zeros(3x1,0nz) */
  /* #726: @50 = zeros(3x1,0nz) */
  /* #727: @30 = zeros(4x1) */
  casadi_clear(w30, 4);
  /* #728: @53 = 00 */
  /* #729: @21 = ones(13x1,1nz) */
  w21 = 1.;
  /* #730: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @9, NULL, NULL} = vertsplit(@21) */
  w9 = w21;
  /* #731: @51 = 00 */
  /* #732: @54 = 00 */
  /* #733: @21 = vertcat(@53, @9, @51, @54) */
  rr=(&w21);
  *rr++ = w9;
  /* #734: @30 = mac(@35,@21,@30) */
  casadi_mtimes(w35, casadi_s26, (&w21), casadi_s11, w30, casadi_s7, w, 0);
  /* #735: @30 = (@3*@30) */
  for (i=0, rr=w30, cs=w30; i<4; ++i) (*rr++)  = (w3*(*cs++));
  /* #736: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #737: @24 = zeros(3x1) */
  casadi_clear(w24, 3);
  /* #738: @21 = sparsity_cast(@9) */
  casadi_copy((&w9), 1, (&w21));
  /* #739: @24 = mac(@27,@21,@24) */
  casadi_mtimes(w27, casadi_s1, (&w21), casadi_s28, w24, casadi_s27, w, 0);
  /* #740: @21 = @24[2] */
  for (rr=(&w21), ss=w24+2; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #741: @49 = (@11*@21) */
  w49  = (w11*w21);
  /* #742: @22 = @24[1] */
  for (rr=(&w22), ss=w24+1; ss!=w24+2; ss+=1) *rr++ = *ss;
  /* #743: @8 = (@12*@22) */
  w8  = (w12*w22);
  /* #744: @49 = (@49-@8) */
  w49 -= w8;
  /* #745: @8 = @24[0] */
  for (rr=(&w8), ss=w24+0; ss!=w24+1; ss+=1) *rr++ = *ss;
  /* #746: @36 = (@12*@8) */
  w36  = (w12*w8);
  /* #747: @20 = (@23*@9) */
  w20  = (w23*w9);
  /* #748: @21 = (@10*@21) */
  w21  = (w10*w21);
  /* #749: @20 = (@20+@21) */
  w20 += w21;
  /* #750: @36 = (@36-@20) */
  w36 -= w20;
  /* #751: @9 = (@37*@9) */
  w9  = (w37*w9);
  /* #752: @22 = (@10*@22) */
  w22  = (w10*w22);
  /* #753: @9 = (@9+@22) */
  w9 += w22;
  /* #754: @8 = (@11*@8) */
  w8  = (w11*w8);
  /* #755: @9 = (@9-@8) */
  w9 -= w8;
  /* #756: @24 = vertcat(@49, @36, @9) */
  rr=w24;
  *rr++ = w49;
  *rr++ = w36;
  *rr++ = w9;
  /* #757: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) *rr++ = (- *cs++ );
  /* #758: @15 = mac(@28,@24,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w28+j, tt=w24+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #759: @75 = vertcat(@52, @50, @30, @15) */
  rr=w75;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  /* #760: @75 = (-@75) */
  for (i=0, rr=w75, cs=w75; i<7; ++i) *rr++ = (- *cs++ );
  /* #761: @46 = @75[:7] */
  for (rr=w46, ss=w75+0; ss!=w75+7; ss+=1) *rr++ = *ss;
  /* #762: (@45[19, 26, 33, 40, 43, 46, 49] = @46) */
  for (cii=casadi_s29, rr=w45, ss=w46; cii!=casadi_s29+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #763: @52 = zeros(3x1,0nz) */
  /* #764: @50 = zeros(3x1,0nz) */
  /* #765: @30 = zeros(4x1) */
  casadi_clear(w30, 4);
  /* #766: @53 = 00 */
  /* #767: @51 = 00 */
  /* #768: @49 = ones(13x1,1nz) */
  w49 = 1.;
  /* #769: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @36, NULL} = vertsplit(@49) */
  w36 = w49;
  /* #770: @54 = 00 */
  /* #771: @49 = vertcat(@53, @51, @36, @54) */
  rr=(&w49);
  *rr++ = w36;
  /* #772: @30 = mac(@35,@49,@30) */
  casadi_mtimes(w35, casadi_s26, (&w49), casadi_s16, w30, casadi_s7, w, 0);
  /* #773: @30 = (@3*@30) */
  for (i=0, rr=w30, cs=w30; i<4; ++i) (*rr++)  = (w3*(*cs++));
  /* #774: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #775: @23 = (@23*@36) */
  w23 *= w36;
  /* #776: @24 = zeros(3x1) */
  casadi_clear(w24, 3);
  /* #777: @49 = sparsity_cast(@36) */
  casadi_copy((&w36), 1, (&w49));
  /* #778: @24 = mac(@27,@49,@24) */
  casadi_mtimes(w27, casadi_s1, (&w49), casadi_s30, w24, casadi_s27, w, 0);
  /* #779: @49 = @24[2] */
  for (rr=(&w49), ss=w24+2; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #780: @9 = (@11*@49) */
  w9  = (w11*w49);
  /* #781: @23 = (@23+@9) */
  w23 += w9;
  /* #782: @9 = @24[1] */
  for (rr=(&w9), ss=w24+1; ss!=w24+2; ss+=1) *rr++ = *ss;
  /* #783: @8 = (@12*@9) */
  w8  = (w12*w9);
  /* #784: @23 = (@23-@8) */
  w23 -= w8;
  /* #785: @8 = @24[0] */
  for (rr=(&w8), ss=w24+0; ss!=w24+1; ss+=1) *rr++ = *ss;
  /* #786: @22 = (@12*@8) */
  w22  = (w12*w8);
  /* #787: @49 = (@10*@49) */
  w49  = (w10*w49);
  /* #788: @22 = (@22-@49) */
  w22 -= w49;
  /* #789: @9 = (@10*@9) */
  w9  = (w10*w9);
  /* #790: @36 = (@41*@36) */
  w36  = (w41*w36);
  /* #791: @8 = (@11*@8) */
  w8  = (w11*w8);
  /* #792: @36 = (@36+@8) */
  w36 += w8;
  /* #793: @9 = (@9-@36) */
  w9 -= w36;
  /* #794: @24 = vertcat(@23, @22, @9) */
  rr=w24;
  *rr++ = w23;
  *rr++ = w22;
  *rr++ = w9;
  /* #795: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) *rr++ = (- *cs++ );
  /* #796: @15 = mac(@28,@24,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w28+j, tt=w24+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #797: @46 = vertcat(@52, @50, @30, @15) */
  rr=w46;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  /* #798: @46 = (-@46) */
  for (i=0, rr=w46, cs=w46; i<7; ++i) *rr++ = (- *cs++ );
  /* #799: @75 = @46[:7] */
  for (rr=w75, ss=w46+0; ss!=w46+7; ss+=1) *rr++ = *ss;
  /* #800: (@45[20, 27, 34, 41, 44, 47, 50] = @75) */
  for (cii=casadi_s31, rr=w45, ss=w75; cii!=casadi_s31+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #801: @52 = zeros(3x1,0nz) */
  /* #802: @50 = zeros(3x1,0nz) */
  /* #803: @30 = zeros(4x1) */
  casadi_clear(w30, 4);
  /* #804: @53 = 00 */
  /* #805: @51 = 00 */
  /* #806: @54 = 00 */
  /* #807: @23 = ones(13x1,1nz) */
  w23 = 1.;
  /* #808: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @22} = vertsplit(@23) */
  w22 = w23;
  /* #809: @23 = vertcat(@53, @51, @54, @22) */
  rr=(&w23);
  *rr++ = w22;
  /* #810: @30 = mac(@35,@23,@30) */
  casadi_mtimes(w35, casadi_s26, (&w23), casadi_s21, w30, casadi_s7, w, 0);
  /* #811: @30 = (@3*@30) */
  for (i=0, rr=w30, cs=w30; i<4; ++i) (*rr++)  = (w3*(*cs++));
  /* #812: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #813: @24 = zeros(3x1) */
  casadi_clear(w24, 3);
  /* #814: @3 = sparsity_cast(@22) */
  casadi_copy((&w22), 1, (&w3));
  /* #815: @24 = mac(@27,@3,@24) */
  casadi_mtimes(w27, casadi_s1, (&w3), casadi_s32, w24, casadi_s27, w, 0);
  /* #816: @3 = @24[2] */
  for (rr=(&w3), ss=w24+2; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #817: @23 = (@11*@3) */
  w23  = (w11*w3);
  /* #818: @37 = (@37*@22) */
  w37 *= w22;
  /* #819: @9 = @24[1] */
  for (rr=(&w9), ss=w24+1; ss!=w24+2; ss+=1) *rr++ = *ss;
  /* #820: @36 = (@12*@9) */
  w36  = (w12*w9);
  /* #821: @37 = (@37+@36) */
  w37 += w36;
  /* #822: @23 = (@23-@37) */
  w23 -= w37;
  /* #823: @41 = (@41*@22) */
  w41 *= w22;
  /* #824: @22 = @24[0] */
  for (rr=(&w22), ss=w24+0; ss!=w24+1; ss+=1) *rr++ = *ss;
  /* #825: @12 = (@12*@22) */
  w12 *= w22;
  /* #826: @41 = (@41+@12) */
  w41 += w12;
  /* #827: @3 = (@10*@3) */
  w3  = (w10*w3);
  /* #828: @41 = (@41-@3) */
  w41 -= w3;
  /* #829: @10 = (@10*@9) */
  w10 *= w9;
  /* #830: @11 = (@11*@22) */
  w11 *= w22;
  /* #831: @10 = (@10-@11) */
  w10 -= w11;
  /* #832: @24 = vertcat(@23, @41, @10) */
  rr=w24;
  *rr++ = w23;
  *rr++ = w41;
  *rr++ = w10;
  /* #833: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) *rr++ = (- *cs++ );
  /* #834: @15 = mac(@28,@24,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w28+j, tt=w24+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #835: @75 = vertcat(@52, @50, @30, @15) */
  rr=w75;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  /* #836: @75 = (-@75) */
  for (i=0, rr=w75, cs=w75; i<7; ++i) *rr++ = (- *cs++ );
  /* #837: @46 = @75[:7] */
  for (rr=w46, ss=w75+0; ss!=w75+7; ss+=1) *rr++ = *ss;
  /* #838: (@45[21, 28, 35, 42, 45, 48, 51] = @46) */
  for (cii=casadi_s33, rr=w45, ss=w46; cii!=casadi_s33+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #839: @76 = @45' */
  casadi_trans(w45,casadi_s35, w76, casadi_s34, iw);
  /* #840: output[1][0] = @76 */
  casadi_copy(w76, 52, res[1]);
  /* #841: @13 = zeros(13x13,13nz) */
  casadi_clear(w13, 13);
  /* #842: @14 = ones(13x1) */
  casadi_fill(w14, 13, 1.);
  /* #843: (@13[:13] = @14) */
  for (rr=w13+0, ss=w14; rr!=w13+13; rr+=1) *rr = *ss++;
  /* #844: @14 = @13' */
  casadi_trans(w13,casadi_s36, w14, casadi_s36, iw);
  /* #845: output[2][0] = @14 */
  casadi_copy(w14, 13, res[2]);
  /* #846: @77 = zeros(4x13,12nz) */
  casadi_clear(w77, 12);
  /* #847: @52 = zeros(3x1,0nz) */
  /* #848: @78 = ones(4x1,2nz) */
  casadi_fill(w78, 2, 1.);
  /* #849: {@23, @41, NULL, NULL} = vertsplit(@78) */
  w23 = w78[0];
  w41 = w78[1];
  /* #850: @16 = (@16*@23) */
  for (i=0, rr=w16; i<3; ++i) (*rr++) *= w23;
  /* #851: @50 = zeros(4x1,0nz) */
  /* #852: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #853: @41 = sparsity_cast(@41) */
  /* #854: @15 = mac(@28,@41,@15) */
  casadi_mtimes(w28, casadi_s1, (&w41), casadi_s28, w15, casadi_s27, w, 0);
  /* #855: @79 = vertcat(@52, @16, @50, @15) */
  rr=w79;
  for (i=0, cs=w16; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  /* #856: @79 = (-@79) */
  for (i=0, rr=w79, cs=w79; i<6; ++i) *rr++ = (- *cs++ );
  /* #857: @80 = @79[:6] */
  for (rr=w80, ss=w79+0; ss!=w79+6; ss+=1) *rr++ = *ss;
  /* #858: (@77[0, 1, 2, 3, 6, 9] = @80) */
  for (cii=casadi_s37, rr=w77, ss=w80; cii!=casadi_s37+6; ++cii, ++ss) rr[*cii] = *ss;
  /* #859: @52 = zeros(3x1,0nz) */
  /* #860: @50 = zeros(3x1,0nz) */
  /* #861: @53 = zeros(4x1,0nz) */
  /* #862: @16 = zeros(3x1) */
  casadi_clear(w16, 3);
  /* #863: @41 = ones(4x1,1nz) */
  w41 = 1.;
  /* #864: {NULL, NULL, @23, NULL} = vertsplit(@41) */
  w23 = w41;
  /* #865: @23 = sparsity_cast(@23) */
  /* #866: @16 = mac(@28,@23,@16) */
  casadi_mtimes(w28, casadi_s1, (&w23), casadi_s30, w16, casadi_s27, w, 0);
  /* #867: @15 = vertcat(@52, @50, @53, @16) */
  rr=w15;
  for (i=0, cs=w16; i<3; ++i) *rr++ = *cs++;
  /* #868: @15 = (-@15) */
  for (i=0, rr=w15, cs=w15; i<3; ++i) *rr++ = (- *cs++ );
  /* #869: @16 = @15[:3] */
  for (rr=w16, ss=w15+0; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #870: (@77[4:13:3] = @16) */
  for (rr=w77+4, ss=w16; rr!=w77+13; rr+=3) *rr = *ss++;
  /* #871: @52 = zeros(3x1,0nz) */
  /* #872: @50 = zeros(3x1,0nz) */
  /* #873: @53 = zeros(4x1,0nz) */
  /* #874: @16 = zeros(3x1) */
  casadi_clear(w16, 3);
  /* #875: @23 = ones(4x1,1nz) */
  w23 = 1.;
  /* #876: {NULL, NULL, NULL, @41} = vertsplit(@23) */
  w41 = w23;
  /* #877: @41 = sparsity_cast(@41) */
  /* #878: @16 = mac(@28,@41,@16) */
  casadi_mtimes(w28, casadi_s1, (&w41), casadi_s32, w16, casadi_s27, w, 0);
  /* #879: @15 = vertcat(@52, @50, @53, @16) */
  rr=w15;
  for (i=0, cs=w16; i<3; ++i) *rr++ = *cs++;
  /* #880: @15 = (-@15) */
  for (i=0, rr=w15, cs=w15; i<3; ++i) *rr++ = (- *cs++ );
  /* #881: @16 = @15[:3] */
  for (rr=w16, ss=w15+0; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #882: (@77[5:14:3] = @16) */
  for (rr=w77+5, ss=w16; rr!=w77+14; rr+=3) *rr = *ss++;
  /* #883: @81 = @77' */
  casadi_trans(w77,casadi_s39, w81, casadi_s38, iw);
  /* #884: output[3][0] = @81 */
  casadi_copy(w81, 12, res[3]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_impl_dae_fun_jac_x_xdot_u_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_impl_dae_fun_jac_x_xdot_u_z_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_impl_dae_fun_jac_x_xdot_u_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_impl_dae_fun_jac_x_xdot_u_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_impl_dae_fun_jac_x_xdot_u_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_impl_dae_fun_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s40;
    case 1: return casadi_s40;
    case 2: return casadi_s7;
    case 3: return casadi_s41;
    case 4: return casadi_s41;
    case 5: return casadi_s42;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_impl_dae_fun_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s40;
    case 1: return casadi_s34;
    case 2: return casadi_s36;
    case 3: return casadi_s38;
    case 4: return casadi_s43;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 18;
  if (sz_iw) *sz_iw = 14;
  if (sz_w) *sz_w = 371;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_jac_x_xdot_u_z_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 18*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 14*sizeof(casadi_int);
  if (sz_w) *sz_w = 371*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
