/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_impl_dae_fun_jac_x_xdot_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s27 CASADI_PREFIX(s27)
#define casadi_s28 CASADI_PREFIX(s28)
#define casadi_s29 CASADI_PREFIX(s29)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s30 CASADI_PREFIX(s30)
#define casadi_s31 CASADI_PREFIX(s31)
#define casadi_s32 CASADI_PREFIX(s32)
#define casadi_s33 CASADI_PREFIX(s33)
#define casadi_s34 CASADI_PREFIX(s34)
#define casadi_s35 CASADI_PREFIX(s35)
#define casadi_s36 CASADI_PREFIX(s36)
#define casadi_s37 CASADI_PREFIX(s37)
#define casadi_s38 CASADI_PREFIX(s38)
#define casadi_s39 CASADI_PREFIX(s39)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s40 CASADI_PREFIX(s40)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[3] = {0, 1, 2};
static const casadi_int casadi_s1[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[12] = {3, 3, 0, 3, 5, 6, 0, 1, 2, 1, 2, 2};
static const casadi_int casadi_s3[12] = {3, 3, 0, 1, 3, 6, 0, 0, 1, 0, 1, 2};
static const casadi_int casadi_s4[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s5[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s6[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s7[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s8[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s9[11] = {4, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3};
static const casadi_int casadi_s10[10] = {0, 1, 2, 3, 7, 11, 15, 22, 29, 36};
static const casadi_int casadi_s11[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s12[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s13[11] = {4, 4, 0, 1, 2, 3, 4, 1, 0, 3, 2};
static const casadi_int casadi_s14[4] = {1, 0, 3, 2};
static const casadi_int casadi_s15[7] = {4, 8, 12, 16, 23, 30, 37};
static const casadi_int casadi_s16[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s17[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s18[11] = {4, 4, 0, 1, 2, 3, 4, 2, 3, 0, 1};
static const casadi_int casadi_s19[4] = {2, 3, 0, 1};
static const casadi_int casadi_s20[7] = {5, 9, 13, 17, 24, 31, 38};
static const casadi_int casadi_s21[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s22[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s23[11] = {4, 4, 0, 1, 2, 3, 4, 3, 2, 1, 0};
static const casadi_int casadi_s24[4] = {3, 2, 1, 0};
static const casadi_int casadi_s25[7] = {6, 10, 14, 18, 25, 32, 39};
static const casadi_int casadi_s26[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s27[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s28[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s29[7] = {19, 26, 33, 40, 43, 46, 49};
static const casadi_int casadi_s30[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s31[7] = {20, 27, 34, 41, 44, 47, 50};
static const casadi_int casadi_s32[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s33[7] = {21, 28, 35, 42, 45, 48, 51};
static const casadi_int casadi_s34[68] = {13, 13, 0, 0, 0, 0, 1, 2, 3, 10, 17, 24, 31, 38, 45, 52, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 3, 4, 5, 6, 7, 8, 9, 3, 4, 5, 6, 7, 8, 9, 3, 4, 5, 6, 7, 8, 9, 6, 7, 8, 9, 10, 11, 12, 6, 7, 8, 9, 10, 11, 12, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s35[68] = {13, 13, 0, 1, 2, 3, 7, 11, 15, 22, 29, 36, 43, 46, 49, 52, 3, 4, 5, 6, 7, 8, 9, 6, 7, 8, 9, 6, 7, 8, 9, 6, 7, 8, 9, 10, 11, 12, 6, 7, 8, 9, 10, 11, 12, 6, 7, 8, 9, 10, 11, 12, 6, 7, 8, 9, 10, 11, 12, 10, 11, 12, 10, 11, 12, 10, 11, 12};
static const casadi_int casadi_s36[29] = {13, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s37[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s38[3] = {0, 0, 0};
static const casadi_int casadi_s39[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s40[3] = {13, 0, 0};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};

/* quadrotor_impl_dae_fun_jac_x_xdot_z:(i0[13],i1[13],i2[4],i3[],i4[],i5[17])->(o0[13],o1[13x13,52nz],o2[13x13,13nz],o3[13x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cr, *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, *w13=w+17, *w14=w+30, *w15=w+43, *w16=w+46, *w17=w+49, *w18=w+53, *w19=w+57, w20, w21, w22, w23, *w24=w+65, *w25=w+68, *w26=w+71, *w27=w+74, *w28=w+83, *w29=w+92, *w30=w+96, *w31=w+100, *w32=w+104, *w33=w+108, *w34=w+112, *w35=w+128, w36, w37, *w38=w+146, *w39=w+149, w40, w41, w42, w43, *w44=w+156, *w45=w+208, w46, w47, w48, w55, w56, w57, w58, w59, w60, w61, w62, w63, w64, w65, w66, *w67=w+230, *w68=w+239, *w69=w+248, *w70=w+258, w71, w72, w73, *w74=w+271, *w75=w+278;
  /* #0: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #1: @1 = input[1][1] */
  w1 = arg[1] ? arg[1][1] : 0;
  /* #2: @2 = input[1][2] */
  w2 = arg[1] ? arg[1][2] : 0;
  /* #3: @3 = input[1][3] */
  w3 = arg[1] ? arg[1][3] : 0;
  /* #4: @4 = input[1][4] */
  w4 = arg[1] ? arg[1][4] : 0;
  /* #5: @5 = input[1][5] */
  w5 = arg[1] ? arg[1][5] : 0;
  /* #6: @6 = input[1][6] */
  w6 = arg[1] ? arg[1][6] : 0;
  /* #7: @7 = input[1][7] */
  w7 = arg[1] ? arg[1][7] : 0;
  /* #8: @8 = input[1][8] */
  w8 = arg[1] ? arg[1][8] : 0;
  /* #9: @9 = input[1][9] */
  w9 = arg[1] ? arg[1][9] : 0;
  /* #10: @10 = input[1][10] */
  w10 = arg[1] ? arg[1][10] : 0;
  /* #11: @11 = input[1][11] */
  w11 = arg[1] ? arg[1][11] : 0;
  /* #12: @12 = input[1][12] */
  w12 = arg[1] ? arg[1][12] : 0;
  /* #13: @13 = vertcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12) */
  rr=w13;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #14: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #15: @1 = input[0][1] */
  w1 = arg[0] ? arg[0][1] : 0;
  /* #16: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #17: @3 = input[0][3] */
  w3 = arg[0] ? arg[0][3] : 0;
  /* #18: @4 = input[0][4] */
  w4 = arg[0] ? arg[0][4] : 0;
  /* #19: @5 = input[0][5] */
  w5 = arg[0] ? arg[0][5] : 0;
  /* #20: @6 = input[0][6] */
  w6 = arg[0] ? arg[0][6] : 0;
  /* #21: @7 = input[0][7] */
  w7 = arg[0] ? arg[0][7] : 0;
  /* #22: @8 = input[0][8] */
  w8 = arg[0] ? arg[0][8] : 0;
  /* #23: @9 = input[0][9] */
  w9 = arg[0] ? arg[0][9] : 0;
  /* #24: @10 = input[0][10] */
  w10 = arg[0] ? arg[0][10] : 0;
  /* #25: @11 = input[0][11] */
  w11 = arg[0] ? arg[0][11] : 0;
  /* #26: @12 = input[0][12] */
  w12 = arg[0] ? arg[0][12] : 0;
  /* #27: @14 = vertcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12) */
  rr=w14;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #28: @15 = @14[3:6] */
  for (rr=w15, ss=w14+3; ss!=w14+6; ss+=1) *rr++ = *ss;
  /* #29: @0 = input[2][0] */
  w0 = arg[2] ? arg[2][0] : 0;
  /* #30: @16 = zeros(3x1) */
  casadi_clear(w16, 3);
  /* #31: @17 = @14[6:10] */
  for (rr=w17, ss=w14+6; ss!=w14+10; ss+=1) *rr++ = *ss;
  /* #32: @1 = 0 */
  w1 = 0.;
  /* #33: @18 = @17' */
  casadi_copy(w17, 4, w18);
  /* #34: @1 = mac(@18,@17,@1) */
  for (i=0, rr=(&w1); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w18+j, tt=w17+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #35: @19 = (@17/@1) */
  for (i=0, rr=w19, cr=w17; i<4; ++i) (*rr++)  = ((*cr++)/w1);
  /* #36: @2 = @19[0] */
  for (rr=(&w2), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #37: @3 = sq(@2) */
  w3 = casadi_sq( w2 );
  /* #38: @4 = @19[1] */
  for (rr=(&w4), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #39: @5 = sq(@4) */
  w5 = casadi_sq( w4 );
  /* #40: @3 = (@3+@5) */
  w3 += w5;
  /* #41: @5 = @19[2] */
  for (rr=(&w5), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #42: @20 = sq(@5) */
  w20 = casadi_sq( w5 );
  /* #43: @3 = (@3-@20) */
  w3 -= w20;
  /* #44: @20 = @19[3] */
  for (rr=(&w20), ss=w19+3; ss!=w19+4; ss+=1) *rr++ = *ss;
  /* #45: @21 = sq(@20) */
  w21 = casadi_sq( w20 );
  /* #46: @3 = (@3-@21) */
  w3 -= w21;
  /* #47: @21 = (@4*@5) */
  w21  = (w4*w5);
  /* #48: @22 = (@2*@20) */
  w22  = (w2*w20);
  /* #49: @21 = (@21-@22) */
  w21 -= w22;
  /* #50: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #51: @22 = (@4*@20) */
  w22  = (w4*w20);
  /* #52: @23 = (@2*@5) */
  w23  = (w2*w5);
  /* #53: @22 = (@22+@23) */
  w22 += w23;
  /* #54: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #55: @24 = horzcat(@3, @21, @22) */
  rr=w24;
  *rr++ = w3;
  *rr++ = w21;
  *rr++ = w22;
  /* #56: @24 = @24' */
  /* #57: @3 = (@4*@5) */
  w3  = (w4*w5);
  /* #58: @21 = (@2*@20) */
  w21  = (w2*w20);
  /* #59: @3 = (@3+@21) */
  w3 += w21;
  /* #60: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #61: @21 = sq(@2) */
  w21 = casadi_sq( w2 );
  /* #62: @22 = sq(@5) */
  w22 = casadi_sq( w5 );
  /* #63: @21 = (@21+@22) */
  w21 += w22;
  /* #64: @22 = sq(@4) */
  w22 = casadi_sq( w4 );
  /* #65: @21 = (@21-@22) */
  w21 -= w22;
  /* #66: @22 = sq(@20) */
  w22 = casadi_sq( w20 );
  /* #67: @21 = (@21-@22) */
  w21 -= w22;
  /* #68: @22 = (@5*@20) */
  w22  = (w5*w20);
  /* #69: @23 = (@2*@4) */
  w23  = (w2*w4);
  /* #70: @22 = (@22-@23) */
  w22 -= w23;
  /* #71: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #72: @25 = horzcat(@3, @21, @22) */
  rr=w25;
  *rr++ = w3;
  *rr++ = w21;
  *rr++ = w22;
  /* #73: @25 = @25' */
  /* #74: @3 = (@4*@20) */
  w3  = (w4*w20);
  /* #75: @21 = (@2*@5) */
  w21  = (w2*w5);
  /* #76: @3 = (@3-@21) */
  w3 -= w21;
  /* #77: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #78: @21 = (@5*@20) */
  w21  = (w5*w20);
  /* #79: @22 = (@2*@4) */
  w22  = (w2*w4);
  /* #80: @21 = (@21+@22) */
  w21 += w22;
  /* #81: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #82: @22 = sq(@2) */
  w22 = casadi_sq( w2 );
  /* #83: @23 = sq(@20) */
  w23 = casadi_sq( w20 );
  /* #84: @22 = (@22+@23) */
  w22 += w23;
  /* #85: @23 = sq(@4) */
  w23 = casadi_sq( w4 );
  /* #86: @22 = (@22-@23) */
  w22 -= w23;
  /* #87: @23 = sq(@5) */
  w23 = casadi_sq( w5 );
  /* #88: @22 = (@22-@23) */
  w22 -= w23;
  /* #89: @26 = horzcat(@3, @21, @22) */
  rr=w26;
  *rr++ = w3;
  *rr++ = w21;
  *rr++ = w22;
  /* #90: @26 = @26' */
  /* #91: @27 = horzcat(@24, @25, @26) */
  rr=w27;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<3; ++i) *rr++ = *cs++;
  /* #92: @28 = @27' */
  for (i=0, rr=w28, cs=w27; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #93: @24 = zeros(3x1) */
  casadi_clear(w24, 3);
  /* #94: @3 = 1 */
  w3 = 1.;
  /* #95: (@24[2] = @3) */
  for (rr=w24+2, ss=(&w3); rr!=w24+3; rr+=1) *rr = *ss++;
  /* #96: @16 = mac(@28,@24,@16) */
  for (i=0, rr=w16; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w28+j, tt=w24+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #97: @16 = (@0*@16) */
  for (i=0, rr=w16, cs=w16; i<3; ++i) (*rr++)  = (w0*(*cs++));
  /* #98: @3 = 9.8 */
  w3 = 9.8000000000000007e+00;
  /* #99: @25 = (@3*@24) */
  for (i=0, rr=w25, cs=w24; i<3; ++i) (*rr++)  = (w3*(*cs++));
  /* #100: @16 = (@16-@25) */
  for (i=0, rr=w16, cs=w25; i<3; ++i) (*rr++) -= (*cs++);
  /* #101: @3 = 0.5 */
  w3 = 5.0000000000000000e-01;
  /* #102: @29 = zeros(4x1) */
  casadi_clear(w29, 4);
  /* #103: @21 = (-@7) */
  w21 = (- w7 );
  /* #104: @22 = (-@8) */
  w22 = (- w8 );
  /* #105: @23 = (-@9) */
  w23 = (- w9 );
  /* #106: @30 = horzcat(@6, @21, @22, @23) */
  rr=w30;
  *rr++ = w6;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  /* #107: @30 = @30' */
  /* #108: @21 = (-@9) */
  w21 = (- w9 );
  /* #109: @31 = horzcat(@7, @6, @21, @8) */
  rr=w31;
  *rr++ = w7;
  *rr++ = w6;
  *rr++ = w21;
  *rr++ = w8;
  /* #110: @31 = @31' */
  /* #111: @21 = (-@7) */
  w21 = (- w7 );
  /* #112: @32 = horzcat(@8, @9, @6, @21) */
  rr=w32;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w6;
  *rr++ = w21;
  /* #113: @32 = @32' */
  /* #114: @21 = (-@8) */
  w21 = (- w8 );
  /* #115: @33 = horzcat(@9, @21, @7, @6) */
  rr=w33;
  *rr++ = w9;
  *rr++ = w21;
  *rr++ = w7;
  *rr++ = w6;
  /* #116: @33 = @33' */
  /* #117: @34 = horzcat(@30, @31, @32, @33) */
  rr=w34;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w32; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<4; ++i) *rr++ = *cs++;
  /* #118: @35 = @34' */
  for (i=0, rr=w35, cs=w34; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #119: @21 = 0 */
  w21 = 0.;
  /* #120: @30 = vertcat(@21, @10, @11, @12) */
  rr=w30;
  *rr++ = w21;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #121: @29 = mac(@35,@30,@29) */
  for (i=0, rr=w29; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w35+j, tt=w30+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #122: @29 = (@3*@29) */
  for (i=0, rr=w29, cs=w29; i<4; ++i) (*rr++)  = (w3*(*cs++));
  /* #123: @21 = 10 */
  w21 = 10.;
  /* #124: @22 = 1 */
  w22 = 1.;
  /* #125: @23 = sq(@6) */
  w23 = casadi_sq( w6 );
  /* #126: @36 = sq(@7) */
  w36 = casadi_sq( w7 );
  /* #127: @23 = (@23+@36) */
  w23 += w36;
  /* #128: @36 = sq(@8) */
  w36 = casadi_sq( w8 );
  /* #129: @23 = (@23+@36) */
  w23 += w36;
  /* #130: @36 = sq(@9) */
  w36 = casadi_sq( w9 );
  /* #131: @23 = (@23+@36) */
  w23 += w36;
  /* #132: @22 = (@22-@23) */
  w22 -= w23;
  /* #133: @22 = (@21*@22) */
  w22  = (w21*w22);
  /* #134: @31 = (@22*@17) */
  for (i=0, rr=w31, cs=w17; i<4; ++i) (*rr++)  = (w22*(*cs++));
  /* #135: @29 = (@29+@31) */
  for (i=0, rr=w29, cs=w31; i<4; ++i) (*rr++) += (*cs++);
  /* #136: @25 = zeros(3x1) */
  casadi_clear(w25, 3);
  /* #137: @28 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w28);
  /* #138: @27 = zeros(3x3) */
  casadi_clear(w27, 9);
  /* #139: @23 = 0.00264 */
  w23 = 2.6400000000000000e-03;
  /* #140: (@27[0] = @23) */
  for (rr=w27+0, ss=(&w23); rr!=w27+1; rr+=1) *rr = *ss++;
  /* #141: @23 = 0.00264 */
  w23 = 2.6400000000000000e-03;
  /* #142: (@27[4] = @23) */
  for (rr=w27+4, ss=(&w23); rr!=w27+5; rr+=1) *rr = *ss++;
  /* #143: @23 = 0.00496 */
  w23 = 4.9600000000000000e-03;
  /* #144: (@27[8] = @23) */
  for (rr=w27+8, ss=(&w23); rr!=w27+9; rr+=1) *rr = *ss++;
  /* #145: @28 = (@27\@28) */
  rr = w28;
  ss = w27;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[6], r[6], beta[3], w[6];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 3, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #146: @23 = input[2][1] */
  w23 = arg[2] ? arg[2][1] : 0;
  /* #147: @36 = input[2][2] */
  w36 = arg[2] ? arg[2][2] : 0;
  /* #148: @37 = input[2][3] */
  w37 = arg[2] ? arg[2][3] : 0;
  /* #149: @31 = vertcat(@0, @23, @36, @37) */
  rr=w31;
  *rr++ = w0;
  *rr++ = w23;
  *rr++ = w36;
  *rr++ = w37;
  /* #150: @26 = @31[1:4] */
  for (rr=w26, ss=w31+1; ss!=w31+4; ss+=1) *rr++ = *ss;
  /* #151: @38 = zeros(3x1) */
  casadi_clear(w38, 3);
  /* #152: @39 = @14[10:13] */
  for (rr=w39, ss=w14+10; ss!=w14+13; ss+=1) *rr++ = *ss;
  /* #153: @38 = mac(@27,@39,@38) */
  for (i=0, rr=w38; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w27+j, tt=w39+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #154: @23 = @38[2] */
  for (rr=(&w23), ss=w38+2; ss!=w38+3; ss+=1) *rr++ = *ss;
  /* #155: @36 = (@11*@23) */
  w36  = (w11*w23);
  /* #156: @37 = @38[1] */
  for (rr=(&w37), ss=w38+1; ss!=w38+2; ss+=1) *rr++ = *ss;
  /* #157: @40 = (@12*@37) */
  w40  = (w12*w37);
  /* #158: @36 = (@36-@40) */
  w36 -= w40;
  /* #159: @40 = @38[0] */
  for (rr=(&w40), ss=w38+0; ss!=w38+1; ss+=1) *rr++ = *ss;
  /* #160: @41 = (@12*@40) */
  w41  = (w12*w40);
  /* #161: @42 = (@10*@23) */
  w42  = (w10*w23);
  /* #162: @41 = (@41-@42) */
  w41 -= w42;
  /* #163: @42 = (@10*@37) */
  w42  = (w10*w37);
  /* #164: @43 = (@11*@40) */
  w43  = (w11*w40);
  /* #165: @42 = (@42-@43) */
  w42 -= w43;
  /* #166: @38 = vertcat(@36, @41, @42) */
  rr=w38;
  *rr++ = w36;
  *rr++ = w41;
  *rr++ = w42;
  /* #167: @26 = (@26-@38) */
  for (i=0, rr=w26, cs=w38; i<3; ++i) (*rr++) -= (*cs++);
  /* #168: @25 = mac(@28,@26,@25) */
  for (i=0, rr=w25; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w28+j, tt=w26+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #169: @14 = vertcat(@15, @16, @29, @25) */
  rr=w14;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  /* #170: @13 = (@13-@14) */
  for (i=0, rr=w13, cs=w14; i<13; ++i) (*rr++) -= (*cs++);
  /* #171: output[0][0] = @13 */
  casadi_copy(w13, 13, res[0]);
  /* #172: @44 = zeros(13x13,52nz) */
  casadi_clear(w44, 52);
  /* #173: @45 = ones(13x1,7nz) */
  casadi_fill(w45, 7, 1.);
  /* #174: {@36, @41, @42, @43, @46, @47, @48, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@45) */
  w36 = w45[0];
  w41 = w45[1];
  w42 = w45[2];
  w43 = w45[3];
  w46 = w45[4];
  w47 = w45[5];
  w48 = w45[6];
  /* #175: @49 = 00 */
  /* #176: @50 = 00 */
  /* #177: @51 = 00 */
  /* #178: @52 = 00 */
  /* #179: @53 = 00 */
  /* #180: @54 = 00 */
  /* #181: @45 = vertcat(@36, @41, @42, @43, @46, @47, @48, @49, @50, @51, @52, @53, @54) */
  rr=w45;
  *rr++ = w36;
  *rr++ = w41;
  *rr++ = w42;
  *rr++ = w43;
  *rr++ = w46;
  *rr++ = w47;
  *rr++ = w48;
  /* #182: @15 = @45[3:6] */
  for (rr=w15, ss=w45+3; ss!=w45+6; ss+=1) *rr++ = *ss;
  /* #183: @16 = zeros(3x1) */
  casadi_clear(w16, 3);
  /* #184: @36 = (2.*@2) */
  w36 = (2.* w2 );
  /* #185: @41 = sparsity_cast(@48) */
  casadi_copy((&w48), 1, (&w41));
  /* #186: @42 = (@41/@1) */
  w42  = (w41/w1);
  /* #187: @29 = dense(@42) */
  casadi_densify((&w42), casadi_s4, w29, 0);
  /* #188: @19 = (@19/@1) */
  for (i=0, rr=w19; i<4; ++i) (*rr++) /= w1;
  /* #189: @42 = 0 */
  w42 = 0.;
  /* #190: @42 = mac(@18,@41,@42) */
  casadi_mtimes(w18, casadi_s6, (&w41), casadi_s4, (&w42), casadi_s5, w, 0);
  /* #191: @43 = 0 */
  w43 = 0.;
  /* #192: @46 = @41' */
  casadi_copy((&w41), 1, (&w46));
  /* #193: @43 = mac(@46,@17,@43) */
  casadi_mtimes((&w46), casadi_s8, w17, casadi_s7, (&w43), casadi_s5, w, 0);
  /* #194: @42 = (@42+@43) */
  w42 += w43;
  /* #195: @31 = (@19*@42) */
  for (i=0, rr=w31, cr=w19; i<4; ++i) (*rr++)  = ((*cr++)*w42);
  /* #196: @29 = (@29-@31) */
  for (i=0, rr=w29, cs=w31; i<4; ++i) (*rr++) -= (*cs++);
  /* #197: @42 = @29[0] */
  for (rr=(&w42), ss=w29+0; ss!=w29+1; ss+=1) *rr++ = *ss;
  /* #198: @43 = (@36*@42) */
  w43  = (w36*w42);
  /* #199: @46 = (2.*@4) */
  w46 = (2.* w4 );
  /* #200: @47 = @29[1] */
  for (rr=(&w47), ss=w29+1; ss!=w29+2; ss+=1) *rr++ = *ss;
  /* #201: @55 = (@46*@47) */
  w55  = (w46*w47);
  /* #202: @43 = (@43+@55) */
  w43 += w55;
  /* #203: @55 = (2.*@5) */
  w55 = (2.* w5 );
  /* #204: @56 = @29[2] */
  for (rr=(&w56), ss=w29+2; ss!=w29+3; ss+=1) *rr++ = *ss;
  /* #205: @57 = (@55*@56) */
  w57  = (w55*w56);
  /* #206: @43 = (@43-@57) */
  w43 -= w57;
  /* #207: @57 = (2.*@20) */
  w57 = (2.* w20 );
  /* #208: @58 = @29[3] */
  for (rr=(&w58), ss=w29+3; ss!=w29+4; ss+=1) *rr++ = *ss;
  /* #209: @59 = (@57*@58) */
  w59  = (w57*w58);
  /* #210: @43 = (@43-@59) */
  w43 -= w59;
  /* #211: @59 = (@5*@47) */
  w59  = (w5*w47);
  /* #212: @60 = (@4*@56) */
  w60  = (w4*w56);
  /* #213: @59 = (@59+@60) */
  w59 += w60;
  /* #214: @60 = (@20*@42) */
  w60  = (w20*w42);
  /* #215: @61 = (@2*@58) */
  w61  = (w2*w58);
  /* #216: @60 = (@60+@61) */
  w60 += w61;
  /* #217: @59 = (@59-@60) */
  w59 -= w60;
  /* #218: @59 = (2.*@59) */
  w59 = (2.* w59 );
  /* #219: @60 = (@20*@47) */
  w60  = (w20*w47);
  /* #220: @61 = (@4*@58) */
  w61  = (w4*w58);
  /* #221: @60 = (@60+@61) */
  w60 += w61;
  /* #222: @61 = (@5*@42) */
  w61  = (w5*w42);
  /* #223: @62 = (@2*@56) */
  w62  = (w2*w56);
  /* #224: @61 = (@61+@62) */
  w61 += w62;
  /* #225: @60 = (@60+@61) */
  w60 += w61;
  /* #226: @60 = (2.*@60) */
  w60 = (2.* w60 );
  /* #227: @25 = horzcat(@43, @59, @60) */
  rr=w25;
  *rr++ = w43;
  *rr++ = w59;
  *rr++ = w60;
  /* #228: @25 = @25' */
  /* #229: @43 = (@5*@47) */
  w43  = (w5*w47);
  /* #230: @59 = (@4*@56) */
  w59  = (w4*w56);
  /* #231: @43 = (@43+@59) */
  w43 += w59;
  /* #232: @59 = (@20*@42) */
  w59  = (w20*w42);
  /* #233: @60 = (@2*@58) */
  w60  = (w2*w58);
  /* #234: @59 = (@59+@60) */
  w59 += w60;
  /* #235: @43 = (@43+@59) */
  w43 += w59;
  /* #236: @43 = (2.*@43) */
  w43 = (2.* w43 );
  /* #237: @59 = (2.*@2) */
  w59 = (2.* w2 );
  /* #238: @60 = (@59*@42) */
  w60  = (w59*w42);
  /* #239: @61 = (2.*@5) */
  w61 = (2.* w5 );
  /* #240: @62 = (@61*@56) */
  w62  = (w61*w56);
  /* #241: @60 = (@60+@62) */
  w60 += w62;
  /* #242: @62 = (2.*@4) */
  w62 = (2.* w4 );
  /* #243: @63 = (@62*@47) */
  w63  = (w62*w47);
  /* #244: @60 = (@60-@63) */
  w60 -= w63;
  /* #245: @63 = (2.*@20) */
  w63 = (2.* w20 );
  /* #246: @64 = (@63*@58) */
  w64  = (w63*w58);
  /* #247: @60 = (@60-@64) */
  w60 -= w64;
  /* #248: @64 = (@20*@56) */
  w64  = (w20*w56);
  /* #249: @65 = (@5*@58) */
  w65  = (w5*w58);
  /* #250: @64 = (@64+@65) */
  w64 += w65;
  /* #251: @65 = (@4*@42) */
  w65  = (w4*w42);
  /* #252: @66 = (@2*@47) */
  w66  = (w2*w47);
  /* #253: @65 = (@65+@66) */
  w65 += w66;
  /* #254: @64 = (@64-@65) */
  w64 -= w65;
  /* #255: @64 = (2.*@64) */
  w64 = (2.* w64 );
  /* #256: @26 = horzcat(@43, @60, @64) */
  rr=w26;
  *rr++ = w43;
  *rr++ = w60;
  *rr++ = w64;
  /* #257: @26 = @26' */
  /* #258: @43 = (@20*@47) */
  w43  = (w20*w47);
  /* #259: @60 = (@4*@58) */
  w60  = (w4*w58);
  /* #260: @43 = (@43+@60) */
  w43 += w60;
  /* #261: @60 = (@5*@42) */
  w60  = (w5*w42);
  /* #262: @64 = (@2*@56) */
  w64  = (w2*w56);
  /* #263: @60 = (@60+@64) */
  w60 += w64;
  /* #264: @43 = (@43-@60) */
  w43 -= w60;
  /* #265: @43 = (2.*@43) */
  w43 = (2.* w43 );
  /* #266: @60 = (@20*@56) */
  w60  = (w20*w56);
  /* #267: @64 = (@5*@58) */
  w64  = (w5*w58);
  /* #268: @60 = (@60+@64) */
  w60 += w64;
  /* #269: @64 = (@4*@42) */
  w64  = (w4*w42);
  /* #270: @65 = (@2*@47) */
  w65  = (w2*w47);
  /* #271: @64 = (@64+@65) */
  w64 += w65;
  /* #272: @60 = (@60+@64) */
  w60 += w64;
  /* #273: @60 = (2.*@60) */
  w60 = (2.* w60 );
  /* #274: @64 = (2.*@2) */
  w64 = (2.* w2 );
  /* #275: @42 = (@64*@42) */
  w42  = (w64*w42);
  /* #276: @65 = (2.*@20) */
  w65 = (2.* w20 );
  /* #277: @58 = (@65*@58) */
  w58  = (w65*w58);
  /* #278: @42 = (@42+@58) */
  w42 += w58;
  /* #279: @58 = (2.*@4) */
  w58 = (2.* w4 );
  /* #280: @47 = (@58*@47) */
  w47  = (w58*w47);
  /* #281: @42 = (@42-@47) */
  w42 -= w47;
  /* #282: @47 = (2.*@5) */
  w47 = (2.* w5 );
  /* #283: @56 = (@47*@56) */
  w56  = (w47*w56);
  /* #284: @42 = (@42-@56) */
  w42 -= w56;
  /* #285: @38 = horzcat(@43, @60, @42) */
  rr=w38;
  *rr++ = w43;
  *rr++ = w60;
  *rr++ = w42;
  /* #286: @38 = @38' */
  /* #287: @67 = horzcat(@25, @26, @38) */
  rr=w67;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<3; ++i) *rr++ = *cs++;
  /* #288: @68 = @67' */
  for (i=0, rr=w68, cs=w67; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #289: @16 = mac(@68,@24,@16) */
  for (i=0, rr=w16; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w68+j, tt=w24+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #290: @16 = (@0*@16) */
  for (i=0, rr=w16, cs=w16; i<3; ++i) (*rr++)  = (w0*(*cs++));
  /* #291: @52 = 00 */
  /* #292: @53 = 00 */
  /* #293: @54 = 00 */
  /* #294: @43 = horzcat(@48, @52, @53, @54) */
  rr=(&w43);
  *rr++ = w48;
  /* #295: @43 = @43' */
  /* #296: @52 = 00 */
  /* #297: @60 = horzcat(@49, @48, @52, @50) */
  rr=(&w60);
  *rr++ = w48;
  /* #298: @60 = @60' */
  /* #299: @52 = 00 */
  /* #300: @42 = horzcat(@50, @51, @48, @52) */
  rr=(&w42);
  *rr++ = w48;
  /* #301: @42 = @42' */
  /* #302: @50 = 00 */
  /* #303: @56 = horzcat(@51, @50, @49, @48) */
  rr=(&w56);
  *rr++ = w48;
  /* #304: @56 = @56' */
  /* #305: @29 = horzcat(@43, @60, @42, @56) */
  rr=w29;
  *rr++ = w43;
  *rr++ = w60;
  *rr++ = w42;
  *rr++ = w56;
  /* #306: @31 = @29' */
  casadi_trans(w29,casadi_s9, w31, casadi_s9, iw);
  /* #307: @31 = nonzeros(@31) */
  /* #308: @31 = (@31*@30) */
  for (i=0, rr=w31, cs=w30; i<4; ++i) (*rr++) *= (*cs++);
  /* #309: @31 = (@3*@31) */
  for (i=0, rr=w31, cs=w31; i<4; ++i) (*rr++)  = (w3*(*cs++));
  /* #310: @41 = (@22*@41) */
  w41  = (w22*w41);
  /* #311: @29 = dense(@41) */
  casadi_densify((&w41), casadi_s4, w29, 0);
  /* #312: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #313: @6 = (@6*@48) */
  w6 *= w48;
  /* #314: @6 = (@21*@6) */
  w6  = (w21*w6);
  /* #315: @32 = (@17*@6) */
  for (i=0, rr=w32, cr=w17; i<4; ++i) (*rr++)  = ((*cr++)*w6);
  /* #316: @29 = (@29-@32) */
  for (i=0, rr=w29, cs=w32; i<4; ++i) (*rr++) -= (*cs++);
  /* #317: @31 = (@31+@29) */
  for (i=0, rr=w31, cs=w29; i<4; ++i) (*rr++) += (*cs++);
  /* #318: @51 = zeros(3x1,0nz) */
  /* #319: @69 = vertcat(@15, @16, @31, @51) */
  rr=w69;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<4; ++i) *rr++ = *cs++;
  /* #320: @69 = (-@69) */
  for (i=0, rr=w69, cs=w69; i<10; ++i) *rr++ = (- *cs++ );
  /* #321: @70 = @69[:10] */
  for (rr=w70, ss=w69+0; ss!=w69+10; ss+=1) *rr++ = *ss;
  /* #322: (@44[0, 1, 2, 3, 7, 11, 15, 22, 29, 36] = @70) */
  for (cii=casadi_s10, rr=w44, ss=w70; cii!=casadi_s10+10; ++cii, ++ss) rr[*cii] = *ss;
  /* #323: @51 = zeros(3x1,0nz) */
  /* #324: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #325: @6 = ones(13x1,1nz) */
  w6 = 1.;
  /* #326: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, @48, NULL, NULL, NULL, NULL, NULL} = vertsplit(@6) */
  w48 = w6;
  /* #327: @6 = sparsity_cast(@48) */
  casadi_copy((&w48), 1, (&w6));
  /* #328: @41 = (@6/@1) */
  w41  = (w6/w1);
  /* #329: @31 = dense(@41) */
  casadi_densify((&w41), casadi_s11, w31, 0);
  /* #330: @41 = 0 */
  w41 = 0.;
  /* #331: @41 = mac(@18,@6,@41) */
  casadi_mtimes(w18, casadi_s6, (&w6), casadi_s11, (&w41), casadi_s5, w, 0);
  /* #332: @43 = 0 */
  w43 = 0.;
  /* #333: @60 = @6' */
  casadi_copy((&w6), 1, (&w60));
  /* #334: @43 = mac(@60,@17,@43) */
  casadi_mtimes((&w60), casadi_s12, w17, casadi_s7, (&w43), casadi_s5, w, 0);
  /* #335: @41 = (@41+@43) */
  w41 += w43;
  /* #336: @29 = (@19*@41) */
  for (i=0, rr=w29, cr=w19; i<4; ++i) (*rr++)  = ((*cr++)*w41);
  /* #337: @31 = (@31-@29) */
  for (i=0, rr=w31, cs=w29; i<4; ++i) (*rr++) -= (*cs++);
  /* #338: @41 = @31[0] */
  for (rr=(&w41), ss=w31+0; ss!=w31+1; ss+=1) *rr++ = *ss;
  /* #339: @43 = (@36*@41) */
  w43  = (w36*w41);
  /* #340: @60 = @31[1] */
  for (rr=(&w60), ss=w31+1; ss!=w31+2; ss+=1) *rr++ = *ss;
  /* #341: @42 = (@46*@60) */
  w42  = (w46*w60);
  /* #342: @43 = (@43+@42) */
  w43 += w42;
  /* #343: @42 = @31[2] */
  for (rr=(&w42), ss=w31+2; ss!=w31+3; ss+=1) *rr++ = *ss;
  /* #344: @56 = (@55*@42) */
  w56  = (w55*w42);
  /* #345: @43 = (@43-@56) */
  w43 -= w56;
  /* #346: @56 = @31[3] */
  for (rr=(&w56), ss=w31+3; ss!=w31+4; ss+=1) *rr++ = *ss;
  /* #347: @66 = (@57*@56) */
  w66  = (w57*w56);
  /* #348: @43 = (@43-@66) */
  w43 -= w66;
  /* #349: @66 = (@5*@60) */
  w66  = (w5*w60);
  /* #350: @71 = (@4*@42) */
  w71  = (w4*w42);
  /* #351: @66 = (@66+@71) */
  w66 += w71;
  /* #352: @71 = (@20*@41) */
  w71  = (w20*w41);
  /* #353: @72 = (@2*@56) */
  w72  = (w2*w56);
  /* #354: @71 = (@71+@72) */
  w71 += w72;
  /* #355: @66 = (@66-@71) */
  w66 -= w71;
  /* #356: @66 = (2.*@66) */
  w66 = (2.* w66 );
  /* #357: @71 = (@20*@60) */
  w71  = (w20*w60);
  /* #358: @72 = (@4*@56) */
  w72  = (w4*w56);
  /* #359: @71 = (@71+@72) */
  w71 += w72;
  /* #360: @72 = (@5*@41) */
  w72  = (w5*w41);
  /* #361: @73 = (@2*@42) */
  w73  = (w2*w42);
  /* #362: @72 = (@72+@73) */
  w72 += w73;
  /* #363: @71 = (@71+@72) */
  w71 += w72;
  /* #364: @71 = (2.*@71) */
  w71 = (2.* w71 );
  /* #365: @16 = horzcat(@43, @66, @71) */
  rr=w16;
  *rr++ = w43;
  *rr++ = w66;
  *rr++ = w71;
  /* #366: @16 = @16' */
  /* #367: @43 = (@5*@60) */
  w43  = (w5*w60);
  /* #368: @66 = (@4*@42) */
  w66  = (w4*w42);
  /* #369: @43 = (@43+@66) */
  w43 += w66;
  /* #370: @66 = (@20*@41) */
  w66  = (w20*w41);
  /* #371: @71 = (@2*@56) */
  w71  = (w2*w56);
  /* #372: @66 = (@66+@71) */
  w66 += w71;
  /* #373: @43 = (@43+@66) */
  w43 += w66;
  /* #374: @43 = (2.*@43) */
  w43 = (2.* w43 );
  /* #375: @66 = (@59*@41) */
  w66  = (w59*w41);
  /* #376: @71 = (@61*@42) */
  w71  = (w61*w42);
  /* #377: @66 = (@66+@71) */
  w66 += w71;
  /* #378: @71 = (@62*@60) */
  w71  = (w62*w60);
  /* #379: @66 = (@66-@71) */
  w66 -= w71;
  /* #380: @71 = (@63*@56) */
  w71  = (w63*w56);
  /* #381: @66 = (@66-@71) */
  w66 -= w71;
  /* #382: @71 = (@20*@42) */
  w71  = (w20*w42);
  /* #383: @72 = (@5*@56) */
  w72  = (w5*w56);
  /* #384: @71 = (@71+@72) */
  w71 += w72;
  /* #385: @72 = (@4*@41) */
  w72  = (w4*w41);
  /* #386: @73 = (@2*@60) */
  w73  = (w2*w60);
  /* #387: @72 = (@72+@73) */
  w72 += w73;
  /* #388: @71 = (@71-@72) */
  w71 -= w72;
  /* #389: @71 = (2.*@71) */
  w71 = (2.* w71 );
  /* #390: @25 = horzcat(@43, @66, @71) */
  rr=w25;
  *rr++ = w43;
  *rr++ = w66;
  *rr++ = w71;
  /* #391: @25 = @25' */
  /* #392: @43 = (@20*@60) */
  w43  = (w20*w60);
  /* #393: @66 = (@4*@56) */
  w66  = (w4*w56);
  /* #394: @43 = (@43+@66) */
  w43 += w66;
  /* #395: @66 = (@5*@41) */
  w66  = (w5*w41);
  /* #396: @71 = (@2*@42) */
  w71  = (w2*w42);
  /* #397: @66 = (@66+@71) */
  w66 += w71;
  /* #398: @43 = (@43-@66) */
  w43 -= w66;
  /* #399: @43 = (2.*@43) */
  w43 = (2.* w43 );
  /* #400: @66 = (@20*@42) */
  w66  = (w20*w42);
  /* #401: @71 = (@5*@56) */
  w71  = (w5*w56);
  /* #402: @66 = (@66+@71) */
  w66 += w71;
  /* #403: @71 = (@4*@41) */
  w71  = (w4*w41);
  /* #404: @72 = (@2*@60) */
  w72  = (w2*w60);
  /* #405: @71 = (@71+@72) */
  w71 += w72;
  /* #406: @66 = (@66+@71) */
  w66 += w71;
  /* #407: @66 = (2.*@66) */
  w66 = (2.* w66 );
  /* #408: @41 = (@64*@41) */
  w41  = (w64*w41);
  /* #409: @56 = (@65*@56) */
  w56  = (w65*w56);
  /* #410: @41 = (@41+@56) */
  w41 += w56;
  /* #411: @60 = (@58*@60) */
  w60  = (w58*w60);
  /* #412: @41 = (@41-@60) */
  w41 -= w60;
  /* #413: @42 = (@47*@42) */
  w42  = (w47*w42);
  /* #414: @41 = (@41-@42) */
  w41 -= w42;
  /* #415: @26 = horzcat(@43, @66, @41) */
  rr=w26;
  *rr++ = w43;
  *rr++ = w66;
  *rr++ = w41;
  /* #416: @26 = @26' */
  /* #417: @68 = horzcat(@16, @25, @26) */
  rr=w68;
  for (i=0, cs=w16; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<3; ++i) *rr++ = *cs++;
  /* #418: @67 = @68' */
  for (i=0, rr=w67, cs=w68; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #419: @15 = mac(@67,@24,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w67+j, tt=w24+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #420: @15 = (@0*@15) */
  for (i=0, rr=w15, cs=w15; i<3; ++i) (*rr++)  = (w0*(*cs++));
  /* #421: @50 = 00 */
  /* #422: @43 = (-@48) */
  w43 = (- w48 );
  /* #423: @49 = 00 */
  /* #424: @52 = 00 */
  /* #425: @66 = horzcat(@50, @43, @49, @52) */
  rr=(&w66);
  *rr++ = w43;
  /* #426: @66 = @66' */
  /* #427: @49 = 00 */
  /* #428: @52 = 00 */
  /* #429: @43 = horzcat(@48, @50, @49, @52) */
  rr=(&w43);
  *rr++ = w48;
  /* #430: @43 = @43' */
  /* #431: @49 = 00 */
  /* #432: @41 = (-@48) */
  w41 = (- w48 );
  /* #433: @42 = horzcat(@52, @49, @50, @41) */
  rr=(&w42);
  *rr++ = w41;
  /* #434: @42 = @42' */
  /* #435: @52 = 00 */
  /* #436: @41 = horzcat(@49, @52, @48, @50) */
  rr=(&w41);
  *rr++ = w48;
  /* #437: @41 = @41' */
  /* #438: @31 = horzcat(@66, @43, @42, @41) */
  rr=w31;
  *rr++ = w66;
  *rr++ = w43;
  *rr++ = w42;
  *rr++ = w41;
  /* #439: @29 = @31' */
  casadi_trans(w31,casadi_s13, w29, casadi_s13, iw);
  /* #440: @29 = nonzeros(@29) */
  /* #441: @29 = (@29*@30) */
  for (i=0, rr=w29, cs=w30; i<4; ++i) (*rr++) *= (*cs++);
  /* #442: @31 = @29[1, 0, 3, 2] */
  for (cii=casadi_s14, rr=w31, ss=w29; cii!=casadi_s14+4; ++cii) *rr++ = ss[*cii];
  /* #443: @31 = (@3*@31) */
  for (i=0, rr=w31, cs=w31; i<4; ++i) (*rr++)  = (w3*(*cs++));
  /* #444: @6 = (@22*@6) */
  w6  = (w22*w6);
  /* #445: @29 = dense(@6) */
  casadi_densify((&w6), casadi_s11, w29, 0);
  /* #446: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #447: @7 = (@7*@48) */
  w7 *= w48;
  /* #448: @7 = (@21*@7) */
  w7  = (w21*w7);
  /* #449: @32 = (@17*@7) */
  for (i=0, rr=w32, cr=w17; i<4; ++i) (*rr++)  = ((*cr++)*w7);
  /* #450: @29 = (@29-@32) */
  for (i=0, rr=w29, cs=w32; i<4; ++i) (*rr++) -= (*cs++);
  /* #451: @31 = (@31+@29) */
  for (i=0, rr=w31, cs=w29; i<4; ++i) (*rr++) += (*cs++);
  /* #452: @49 = zeros(3x1,0nz) */
  /* #453: @45 = vertcat(@51, @15, @31, @49) */
  rr=w45;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<4; ++i) *rr++ = *cs++;
  /* #454: @45 = (-@45) */
  for (i=0, rr=w45, cs=w45; i<7; ++i) *rr++ = (- *cs++ );
  /* #455: @74 = @45[:7] */
  for (rr=w74, ss=w45+0; ss!=w45+7; ss+=1) *rr++ = *ss;
  /* #456: (@44[4, 8, 12, 16, 23, 30, 37] = @74) */
  for (cii=casadi_s15, rr=w44, ss=w74; cii!=casadi_s15+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #457: @51 = zeros(3x1,0nz) */
  /* #458: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #459: @7 = ones(13x1,1nz) */
  w7 = 1.;
  /* #460: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @48, NULL, NULL, NULL, NULL} = vertsplit(@7) */
  w48 = w7;
  /* #461: @7 = sparsity_cast(@48) */
  casadi_copy((&w48), 1, (&w7));
  /* #462: @6 = (@7/@1) */
  w6  = (w7/w1);
  /* #463: @31 = dense(@6) */
  casadi_densify((&w6), casadi_s16, w31, 0);
  /* #464: @6 = 0 */
  w6 = 0.;
  /* #465: @6 = mac(@18,@7,@6) */
  casadi_mtimes(w18, casadi_s6, (&w7), casadi_s16, (&w6), casadi_s5, w, 0);
  /* #466: @66 = 0 */
  w66 = 0.;
  /* #467: @43 = @7' */
  casadi_copy((&w7), 1, (&w43));
  /* #468: @66 = mac(@43,@17,@66) */
  casadi_mtimes((&w43), casadi_s17, w17, casadi_s7, (&w66), casadi_s5, w, 0);
  /* #469: @6 = (@6+@66) */
  w6 += w66;
  /* #470: @29 = (@19*@6) */
  for (i=0, rr=w29, cr=w19; i<4; ++i) (*rr++)  = ((*cr++)*w6);
  /* #471: @31 = (@31-@29) */
  for (i=0, rr=w31, cs=w29; i<4; ++i) (*rr++) -= (*cs++);
  /* #472: @6 = @31[0] */
  for (rr=(&w6), ss=w31+0; ss!=w31+1; ss+=1) *rr++ = *ss;
  /* #473: @66 = (@36*@6) */
  w66  = (w36*w6);
  /* #474: @43 = @31[1] */
  for (rr=(&w43), ss=w31+1; ss!=w31+2; ss+=1) *rr++ = *ss;
  /* #475: @42 = (@46*@43) */
  w42  = (w46*w43);
  /* #476: @66 = (@66+@42) */
  w66 += w42;
  /* #477: @42 = @31[2] */
  for (rr=(&w42), ss=w31+2; ss!=w31+3; ss+=1) *rr++ = *ss;
  /* #478: @41 = (@55*@42) */
  w41  = (w55*w42);
  /* #479: @66 = (@66-@41) */
  w66 -= w41;
  /* #480: @41 = @31[3] */
  for (rr=(&w41), ss=w31+3; ss!=w31+4; ss+=1) *rr++ = *ss;
  /* #481: @60 = (@57*@41) */
  w60  = (w57*w41);
  /* #482: @66 = (@66-@60) */
  w66 -= w60;
  /* #483: @60 = (@5*@43) */
  w60  = (w5*w43);
  /* #484: @56 = (@4*@42) */
  w56  = (w4*w42);
  /* #485: @60 = (@60+@56) */
  w60 += w56;
  /* #486: @56 = (@20*@6) */
  w56  = (w20*w6);
  /* #487: @71 = (@2*@41) */
  w71  = (w2*w41);
  /* #488: @56 = (@56+@71) */
  w56 += w71;
  /* #489: @60 = (@60-@56) */
  w60 -= w56;
  /* #490: @60 = (2.*@60) */
  w60 = (2.* w60 );
  /* #491: @56 = (@20*@43) */
  w56  = (w20*w43);
  /* #492: @71 = (@4*@41) */
  w71  = (w4*w41);
  /* #493: @56 = (@56+@71) */
  w56 += w71;
  /* #494: @71 = (@5*@6) */
  w71  = (w5*w6);
  /* #495: @72 = (@2*@42) */
  w72  = (w2*w42);
  /* #496: @71 = (@71+@72) */
  w71 += w72;
  /* #497: @56 = (@56+@71) */
  w56 += w71;
  /* #498: @56 = (2.*@56) */
  w56 = (2.* w56 );
  /* #499: @16 = horzcat(@66, @60, @56) */
  rr=w16;
  *rr++ = w66;
  *rr++ = w60;
  *rr++ = w56;
  /* #500: @16 = @16' */
  /* #501: @66 = (@5*@43) */
  w66  = (w5*w43);
  /* #502: @60 = (@4*@42) */
  w60  = (w4*w42);
  /* #503: @66 = (@66+@60) */
  w66 += w60;
  /* #504: @60 = (@20*@6) */
  w60  = (w20*w6);
  /* #505: @56 = (@2*@41) */
  w56  = (w2*w41);
  /* #506: @60 = (@60+@56) */
  w60 += w56;
  /* #507: @66 = (@66+@60) */
  w66 += w60;
  /* #508: @66 = (2.*@66) */
  w66 = (2.* w66 );
  /* #509: @60 = (@59*@6) */
  w60  = (w59*w6);
  /* #510: @56 = (@61*@42) */
  w56  = (w61*w42);
  /* #511: @60 = (@60+@56) */
  w60 += w56;
  /* #512: @56 = (@62*@43) */
  w56  = (w62*w43);
  /* #513: @60 = (@60-@56) */
  w60 -= w56;
  /* #514: @56 = (@63*@41) */
  w56  = (w63*w41);
  /* #515: @60 = (@60-@56) */
  w60 -= w56;
  /* #516: @56 = (@20*@42) */
  w56  = (w20*w42);
  /* #517: @71 = (@5*@41) */
  w71  = (w5*w41);
  /* #518: @56 = (@56+@71) */
  w56 += w71;
  /* #519: @71 = (@4*@6) */
  w71  = (w4*w6);
  /* #520: @72 = (@2*@43) */
  w72  = (w2*w43);
  /* #521: @71 = (@71+@72) */
  w71 += w72;
  /* #522: @56 = (@56-@71) */
  w56 -= w71;
  /* #523: @56 = (2.*@56) */
  w56 = (2.* w56 );
  /* #524: @25 = horzcat(@66, @60, @56) */
  rr=w25;
  *rr++ = w66;
  *rr++ = w60;
  *rr++ = w56;
  /* #525: @25 = @25' */
  /* #526: @66 = (@20*@43) */
  w66  = (w20*w43);
  /* #527: @60 = (@4*@41) */
  w60  = (w4*w41);
  /* #528: @66 = (@66+@60) */
  w66 += w60;
  /* #529: @60 = (@5*@6) */
  w60  = (w5*w6);
  /* #530: @56 = (@2*@42) */
  w56  = (w2*w42);
  /* #531: @60 = (@60+@56) */
  w60 += w56;
  /* #532: @66 = (@66-@60) */
  w66 -= w60;
  /* #533: @66 = (2.*@66) */
  w66 = (2.* w66 );
  /* #534: @60 = (@20*@42) */
  w60  = (w20*w42);
  /* #535: @56 = (@5*@41) */
  w56  = (w5*w41);
  /* #536: @60 = (@60+@56) */
  w60 += w56;
  /* #537: @56 = (@4*@6) */
  w56  = (w4*w6);
  /* #538: @71 = (@2*@43) */
  w71  = (w2*w43);
  /* #539: @56 = (@56+@71) */
  w56 += w71;
  /* #540: @60 = (@60+@56) */
  w60 += w56;
  /* #541: @60 = (2.*@60) */
  w60 = (2.* w60 );
  /* #542: @6 = (@64*@6) */
  w6  = (w64*w6);
  /* #543: @41 = (@65*@41) */
  w41  = (w65*w41);
  /* #544: @6 = (@6+@41) */
  w6 += w41;
  /* #545: @43 = (@58*@43) */
  w43  = (w58*w43);
  /* #546: @6 = (@6-@43) */
  w6 -= w43;
  /* #547: @42 = (@47*@42) */
  w42  = (w47*w42);
  /* #548: @6 = (@6-@42) */
  w6 -= w42;
  /* #549: @26 = horzcat(@66, @60, @6) */
  rr=w26;
  *rr++ = w66;
  *rr++ = w60;
  *rr++ = w6;
  /* #550: @26 = @26' */
  /* #551: @67 = horzcat(@16, @25, @26) */
  rr=w67;
  for (i=0, cs=w16; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<3; ++i) *rr++ = *cs++;
  /* #552: @68 = @67' */
  for (i=0, rr=w68, cs=w67; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #553: @15 = mac(@68,@24,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w68+j, tt=w24+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #554: @15 = (@0*@15) */
  for (i=0, rr=w15, cs=w15; i<3; ++i) (*rr++)  = (w0*(*cs++));
  /* #555: @49 = 00 */
  /* #556: @52 = 00 */
  /* #557: @66 = (-@48) */
  w66 = (- w48 );
  /* #558: @50 = 00 */
  /* #559: @60 = horzcat(@49, @52, @66, @50) */
  rr=(&w60);
  *rr++ = w66;
  /* #560: @60 = @60' */
  /* #561: @52 = 00 */
  /* #562: @50 = 00 */
  /* #563: @66 = horzcat(@52, @49, @50, @48) */
  rr=(&w66);
  *rr++ = w48;
  /* #564: @66 = @66' */
  /* #565: @50 = 00 */
  /* #566: @53 = 00 */
  /* #567: @6 = horzcat(@48, @50, @49, @53) */
  rr=(&w6);
  *rr++ = w48;
  /* #568: @6 = @6' */
  /* #569: @42 = (-@48) */
  w42 = (- w48 );
  /* #570: @43 = horzcat(@50, @42, @52, @49) */
  rr=(&w43);
  *rr++ = w42;
  /* #571: @43 = @43' */
  /* #572: @31 = horzcat(@60, @66, @6, @43) */
  rr=w31;
  *rr++ = w60;
  *rr++ = w66;
  *rr++ = w6;
  *rr++ = w43;
  /* #573: @29 = @31' */
  casadi_trans(w31,casadi_s18, w29, casadi_s18, iw);
  /* #574: @29 = nonzeros(@29) */
  /* #575: @29 = (@29*@30) */
  for (i=0, rr=w29, cs=w30; i<4; ++i) (*rr++) *= (*cs++);
  /* #576: @31 = @29[2, 3, 0, 1] */
  for (cii=casadi_s19, rr=w31, ss=w29; cii!=casadi_s19+4; ++cii) *rr++ = ss[*cii];
  /* #577: @31 = (@3*@31) */
  for (i=0, rr=w31, cs=w31; i<4; ++i) (*rr++)  = (w3*(*cs++));
  /* #578: @7 = (@22*@7) */
  w7  = (w22*w7);
  /* #579: @29 = dense(@7) */
  casadi_densify((&w7), casadi_s16, w29, 0);
  /* #580: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #581: @8 = (@8*@48) */
  w8 *= w48;
  /* #582: @8 = (@21*@8) */
  w8  = (w21*w8);
  /* #583: @32 = (@17*@8) */
  for (i=0, rr=w32, cr=w17; i<4; ++i) (*rr++)  = ((*cr++)*w8);
  /* #584: @29 = (@29-@32) */
  for (i=0, rr=w29, cs=w32; i<4; ++i) (*rr++) -= (*cs++);
  /* #585: @31 = (@31+@29) */
  for (i=0, rr=w31, cs=w29; i<4; ++i) (*rr++) += (*cs++);
  /* #586: @50 = zeros(3x1,0nz) */
  /* #587: @74 = vertcat(@51, @15, @31, @50) */
  rr=w74;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<4; ++i) *rr++ = *cs++;
  /* #588: @74 = (-@74) */
  for (i=0, rr=w74, cs=w74; i<7; ++i) *rr++ = (- *cs++ );
  /* #589: @45 = @74[:7] */
  for (rr=w45, ss=w74+0; ss!=w74+7; ss+=1) *rr++ = *ss;
  /* #590: (@44[5, 9, 13, 17, 24, 31, 38] = @45) */
  for (cii=casadi_s20, rr=w44, ss=w45; cii!=casadi_s20+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #591: @51 = zeros(3x1,0nz) */
  /* #592: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #593: @8 = ones(13x1,1nz) */
  w8 = 1.;
  /* #594: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @48, NULL, NULL, NULL} = vertsplit(@8) */
  w48 = w8;
  /* #595: @8 = sparsity_cast(@48) */
  casadi_copy((&w48), 1, (&w8));
  /* #596: @1 = (@8/@1) */
  w1  = (w8/w1);
  /* #597: @31 = dense(@1) */
  casadi_densify((&w1), casadi_s21, w31, 0);
  /* #598: @1 = 0 */
  w1 = 0.;
  /* #599: @1 = mac(@18,@8,@1) */
  casadi_mtimes(w18, casadi_s6, (&w8), casadi_s21, (&w1), casadi_s5, w, 0);
  /* #600: @7 = 0 */
  w7 = 0.;
  /* #601: @60 = @8' */
  casadi_copy((&w8), 1, (&w60));
  /* #602: @7 = mac(@60,@17,@7) */
  casadi_mtimes((&w60), casadi_s22, w17, casadi_s7, (&w7), casadi_s5, w, 0);
  /* #603: @1 = (@1+@7) */
  w1 += w7;
  /* #604: @19 = (@19*@1) */
  for (i=0, rr=w19; i<4; ++i) (*rr++) *= w1;
  /* #605: @31 = (@31-@19) */
  for (i=0, rr=w31, cs=w19; i<4; ++i) (*rr++) -= (*cs++);
  /* #606: @1 = @31[0] */
  for (rr=(&w1), ss=w31+0; ss!=w31+1; ss+=1) *rr++ = *ss;
  /* #607: @36 = (@36*@1) */
  w36 *= w1;
  /* #608: @7 = @31[1] */
  for (rr=(&w7), ss=w31+1; ss!=w31+2; ss+=1) *rr++ = *ss;
  /* #609: @46 = (@46*@7) */
  w46 *= w7;
  /* #610: @36 = (@36+@46) */
  w36 += w46;
  /* #611: @46 = @31[2] */
  for (rr=(&w46), ss=w31+2; ss!=w31+3; ss+=1) *rr++ = *ss;
  /* #612: @55 = (@55*@46) */
  w55 *= w46;
  /* #613: @36 = (@36-@55) */
  w36 -= w55;
  /* #614: @55 = @31[3] */
  for (rr=(&w55), ss=w31+3; ss!=w31+4; ss+=1) *rr++ = *ss;
  /* #615: @57 = (@57*@55) */
  w57 *= w55;
  /* #616: @36 = (@36-@57) */
  w36 -= w57;
  /* #617: @57 = (@5*@7) */
  w57  = (w5*w7);
  /* #618: @60 = (@4*@46) */
  w60  = (w4*w46);
  /* #619: @57 = (@57+@60) */
  w57 += w60;
  /* #620: @60 = (@20*@1) */
  w60  = (w20*w1);
  /* #621: @66 = (@2*@55) */
  w66  = (w2*w55);
  /* #622: @60 = (@60+@66) */
  w60 += w66;
  /* #623: @57 = (@57-@60) */
  w57 -= w60;
  /* #624: @57 = (2.*@57) */
  w57 = (2.* w57 );
  /* #625: @60 = (@20*@7) */
  w60  = (w20*w7);
  /* #626: @66 = (@4*@55) */
  w66  = (w4*w55);
  /* #627: @60 = (@60+@66) */
  w60 += w66;
  /* #628: @66 = (@5*@1) */
  w66  = (w5*w1);
  /* #629: @6 = (@2*@46) */
  w6  = (w2*w46);
  /* #630: @66 = (@66+@6) */
  w66 += w6;
  /* #631: @60 = (@60+@66) */
  w60 += w66;
  /* #632: @60 = (2.*@60) */
  w60 = (2.* w60 );
  /* #633: @16 = horzcat(@36, @57, @60) */
  rr=w16;
  *rr++ = w36;
  *rr++ = w57;
  *rr++ = w60;
  /* #634: @16 = @16' */
  /* #635: @36 = (@5*@7) */
  w36  = (w5*w7);
  /* #636: @57 = (@4*@46) */
  w57  = (w4*w46);
  /* #637: @36 = (@36+@57) */
  w36 += w57;
  /* #638: @57 = (@20*@1) */
  w57  = (w20*w1);
  /* #639: @60 = (@2*@55) */
  w60  = (w2*w55);
  /* #640: @57 = (@57+@60) */
  w57 += w60;
  /* #641: @36 = (@36+@57) */
  w36 += w57;
  /* #642: @36 = (2.*@36) */
  w36 = (2.* w36 );
  /* #643: @59 = (@59*@1) */
  w59 *= w1;
  /* #644: @61 = (@61*@46) */
  w61 *= w46;
  /* #645: @59 = (@59+@61) */
  w59 += w61;
  /* #646: @62 = (@62*@7) */
  w62 *= w7;
  /* #647: @59 = (@59-@62) */
  w59 -= w62;
  /* #648: @63 = (@63*@55) */
  w63 *= w55;
  /* #649: @59 = (@59-@63) */
  w59 -= w63;
  /* #650: @63 = (@20*@46) */
  w63  = (w20*w46);
  /* #651: @62 = (@5*@55) */
  w62  = (w5*w55);
  /* #652: @63 = (@63+@62) */
  w63 += w62;
  /* #653: @62 = (@4*@1) */
  w62  = (w4*w1);
  /* #654: @61 = (@2*@7) */
  w61  = (w2*w7);
  /* #655: @62 = (@62+@61) */
  w62 += w61;
  /* #656: @63 = (@63-@62) */
  w63 -= w62;
  /* #657: @63 = (2.*@63) */
  w63 = (2.* w63 );
  /* #658: @25 = horzcat(@36, @59, @63) */
  rr=w25;
  *rr++ = w36;
  *rr++ = w59;
  *rr++ = w63;
  /* #659: @25 = @25' */
  /* #660: @36 = (@20*@7) */
  w36  = (w20*w7);
  /* #661: @59 = (@4*@55) */
  w59  = (w4*w55);
  /* #662: @36 = (@36+@59) */
  w36 += w59;
  /* #663: @59 = (@5*@1) */
  w59  = (w5*w1);
  /* #664: @63 = (@2*@46) */
  w63  = (w2*w46);
  /* #665: @59 = (@59+@63) */
  w59 += w63;
  /* #666: @36 = (@36-@59) */
  w36 -= w59;
  /* #667: @36 = (2.*@36) */
  w36 = (2.* w36 );
  /* #668: @20 = (@20*@46) */
  w20 *= w46;
  /* #669: @5 = (@5*@55) */
  w5 *= w55;
  /* #670: @20 = (@20+@5) */
  w20 += w5;
  /* #671: @4 = (@4*@1) */
  w4 *= w1;
  /* #672: @2 = (@2*@7) */
  w2 *= w7;
  /* #673: @4 = (@4+@2) */
  w4 += w2;
  /* #674: @20 = (@20+@4) */
  w20 += w4;
  /* #675: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #676: @64 = (@64*@1) */
  w64 *= w1;
  /* #677: @65 = (@65*@55) */
  w65 *= w55;
  /* #678: @64 = (@64+@65) */
  w64 += w65;
  /* #679: @58 = (@58*@7) */
  w58 *= w7;
  /* #680: @64 = (@64-@58) */
  w64 -= w58;
  /* #681: @47 = (@47*@46) */
  w47 *= w46;
  /* #682: @64 = (@64-@47) */
  w64 -= w47;
  /* #683: @26 = horzcat(@36, @20, @64) */
  rr=w26;
  *rr++ = w36;
  *rr++ = w20;
  *rr++ = w64;
  /* #684: @26 = @26' */
  /* #685: @68 = horzcat(@16, @25, @26) */
  rr=w68;
  for (i=0, cs=w16; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<3; ++i) *rr++ = *cs++;
  /* #686: @67 = @68' */
  for (i=0, rr=w67, cs=w68; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #687: @15 = mac(@67,@24,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w67+j, tt=w24+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #688: @15 = (@0*@15) */
  for (i=0, rr=w15, cs=w15; i<3; ++i) (*rr++)  = (w0*(*cs++));
  /* #689: @50 = 00 */
  /* #690: @52 = 00 */
  /* #691: @49 = 00 */
  /* #692: @0 = (-@48) */
  w0 = (- w48 );
  /* #693: @36 = horzcat(@50, @52, @49, @0) */
  rr=(&w36);
  *rr++ = w0;
  /* #694: @36 = @36' */
  /* #695: @52 = 00 */
  /* #696: @0 = (-@48) */
  w0 = (- w48 );
  /* #697: @49 = 00 */
  /* #698: @20 = horzcat(@52, @50, @0, @49) */
  rr=(&w20);
  *rr++ = w0;
  /* #699: @20 = @20' */
  /* #700: @53 = 00 */
  /* #701: @0 = horzcat(@49, @48, @50, @53) */
  rr=(&w0);
  *rr++ = w48;
  /* #702: @0 = @0' */
  /* #703: @49 = 00 */
  /* #704: @64 = horzcat(@48, @49, @52, @50) */
  rr=(&w64);
  *rr++ = w48;
  /* #705: @64 = @64' */
  /* #706: @31 = horzcat(@36, @20, @0, @64) */
  rr=w31;
  *rr++ = w36;
  *rr++ = w20;
  *rr++ = w0;
  *rr++ = w64;
  /* #707: @19 = @31' */
  casadi_trans(w31,casadi_s23, w19, casadi_s23, iw);
  /* #708: @19 = nonzeros(@19) */
  /* #709: @19 = (@19*@30) */
  for (i=0, rr=w19, cs=w30; i<4; ++i) (*rr++) *= (*cs++);
  /* #710: @30 = @19[3, 2, 1, 0] */
  for (cii=casadi_s24, rr=w30, ss=w19; cii!=casadi_s24+4; ++cii) *rr++ = ss[*cii];
  /* #711: @30 = (@3*@30) */
  for (i=0, rr=w30, cs=w30; i<4; ++i) (*rr++)  = (w3*(*cs++));
  /* #712: @22 = (@22*@8) */
  w22 *= w8;
  /* #713: @19 = dense(@22) */
  casadi_densify((&w22), casadi_s21, w19, 0);
  /* #714: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #715: @9 = (@9*@48) */
  w9 *= w48;
  /* #716: @21 = (@21*@9) */
  w21 *= w9;
  /* #717: @17 = (@17*@21) */
  for (i=0, rr=w17; i<4; ++i) (*rr++) *= w21;
  /* #718: @19 = (@19-@17) */
  for (i=0, rr=w19, cs=w17; i<4; ++i) (*rr++) -= (*cs++);
  /* #719: @30 = (@30+@19) */
  for (i=0, rr=w30, cs=w19; i<4; ++i) (*rr++) += (*cs++);
  /* #720: @49 = zeros(3x1,0nz) */
  /* #721: @45 = vertcat(@51, @15, @30, @49) */
  rr=w45;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  /* #722: @45 = (-@45) */
  for (i=0, rr=w45, cs=w45; i<7; ++i) *rr++ = (- *cs++ );
  /* #723: @74 = @45[:7] */
  for (rr=w74, ss=w45+0; ss!=w45+7; ss+=1) *rr++ = *ss;
  /* #724: (@44[6, 10, 14, 18, 25, 32, 39] = @74) */
  for (cii=casadi_s25, rr=w44, ss=w74; cii!=casadi_s25+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #725: @51 = zeros(3x1,0nz) */
  /* #726: @49 = zeros(3x1,0nz) */
  /* #727: @30 = zeros(4x1) */
  casadi_clear(w30, 4);
  /* #728: @52 = 00 */
  /* #729: @21 = ones(13x1,1nz) */
  w21 = 1.;
  /* #730: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @9, NULL, NULL} = vertsplit(@21) */
  w9 = w21;
  /* #731: @50 = 00 */
  /* #732: @53 = 00 */
  /* #733: @21 = vertcat(@52, @9, @50, @53) */
  rr=(&w21);
  *rr++ = w9;
  /* #734: @30 = mac(@35,@21,@30) */
  casadi_mtimes(w35, casadi_s26, (&w21), casadi_s11, w30, casadi_s7, w, 0);
  /* #735: @30 = (@3*@30) */
  for (i=0, rr=w30, cs=w30; i<4; ++i) (*rr++)  = (w3*(*cs++));
  /* #736: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #737: @24 = zeros(3x1) */
  casadi_clear(w24, 3);
  /* #738: @21 = sparsity_cast(@9) */
  casadi_copy((&w9), 1, (&w21));
  /* #739: @24 = mac(@27,@21,@24) */
  casadi_mtimes(w27, casadi_s1, (&w21), casadi_s28, w24, casadi_s27, w, 0);
  /* #740: @21 = @24[2] */
  for (rr=(&w21), ss=w24+2; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #741: @48 = (@11*@21) */
  w48  = (w11*w21);
  /* #742: @22 = @24[1] */
  for (rr=(&w22), ss=w24+1; ss!=w24+2; ss+=1) *rr++ = *ss;
  /* #743: @8 = (@12*@22) */
  w8  = (w12*w22);
  /* #744: @48 = (@48-@8) */
  w48 -= w8;
  /* #745: @8 = @24[0] */
  for (rr=(&w8), ss=w24+0; ss!=w24+1; ss+=1) *rr++ = *ss;
  /* #746: @36 = (@12*@8) */
  w36  = (w12*w8);
  /* #747: @20 = (@23*@9) */
  w20  = (w23*w9);
  /* #748: @21 = (@10*@21) */
  w21  = (w10*w21);
  /* #749: @20 = (@20+@21) */
  w20 += w21;
  /* #750: @36 = (@36-@20) */
  w36 -= w20;
  /* #751: @9 = (@37*@9) */
  w9  = (w37*w9);
  /* #752: @22 = (@10*@22) */
  w22  = (w10*w22);
  /* #753: @9 = (@9+@22) */
  w9 += w22;
  /* #754: @8 = (@11*@8) */
  w8  = (w11*w8);
  /* #755: @9 = (@9-@8) */
  w9 -= w8;
  /* #756: @24 = vertcat(@48, @36, @9) */
  rr=w24;
  *rr++ = w48;
  *rr++ = w36;
  *rr++ = w9;
  /* #757: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) *rr++ = (- *cs++ );
  /* #758: @15 = mac(@28,@24,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w28+j, tt=w24+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #759: @74 = vertcat(@51, @49, @30, @15) */
  rr=w74;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  /* #760: @74 = (-@74) */
  for (i=0, rr=w74, cs=w74; i<7; ++i) *rr++ = (- *cs++ );
  /* #761: @45 = @74[:7] */
  for (rr=w45, ss=w74+0; ss!=w74+7; ss+=1) *rr++ = *ss;
  /* #762: (@44[19, 26, 33, 40, 43, 46, 49] = @45) */
  for (cii=casadi_s29, rr=w44, ss=w45; cii!=casadi_s29+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #763: @51 = zeros(3x1,0nz) */
  /* #764: @49 = zeros(3x1,0nz) */
  /* #765: @30 = zeros(4x1) */
  casadi_clear(w30, 4);
  /* #766: @52 = 00 */
  /* #767: @50 = 00 */
  /* #768: @48 = ones(13x1,1nz) */
  w48 = 1.;
  /* #769: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @36, NULL} = vertsplit(@48) */
  w36 = w48;
  /* #770: @53 = 00 */
  /* #771: @48 = vertcat(@52, @50, @36, @53) */
  rr=(&w48);
  *rr++ = w36;
  /* #772: @30 = mac(@35,@48,@30) */
  casadi_mtimes(w35, casadi_s26, (&w48), casadi_s16, w30, casadi_s7, w, 0);
  /* #773: @30 = (@3*@30) */
  for (i=0, rr=w30, cs=w30; i<4; ++i) (*rr++)  = (w3*(*cs++));
  /* #774: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #775: @23 = (@23*@36) */
  w23 *= w36;
  /* #776: @24 = zeros(3x1) */
  casadi_clear(w24, 3);
  /* #777: @48 = sparsity_cast(@36) */
  casadi_copy((&w36), 1, (&w48));
  /* #778: @24 = mac(@27,@48,@24) */
  casadi_mtimes(w27, casadi_s1, (&w48), casadi_s30, w24, casadi_s27, w, 0);
  /* #779: @48 = @24[2] */
  for (rr=(&w48), ss=w24+2; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #780: @9 = (@11*@48) */
  w9  = (w11*w48);
  /* #781: @23 = (@23+@9) */
  w23 += w9;
  /* #782: @9 = @24[1] */
  for (rr=(&w9), ss=w24+1; ss!=w24+2; ss+=1) *rr++ = *ss;
  /* #783: @8 = (@12*@9) */
  w8  = (w12*w9);
  /* #784: @23 = (@23-@8) */
  w23 -= w8;
  /* #785: @8 = @24[0] */
  for (rr=(&w8), ss=w24+0; ss!=w24+1; ss+=1) *rr++ = *ss;
  /* #786: @22 = (@12*@8) */
  w22  = (w12*w8);
  /* #787: @48 = (@10*@48) */
  w48  = (w10*w48);
  /* #788: @22 = (@22-@48) */
  w22 -= w48;
  /* #789: @9 = (@10*@9) */
  w9  = (w10*w9);
  /* #790: @36 = (@40*@36) */
  w36  = (w40*w36);
  /* #791: @8 = (@11*@8) */
  w8  = (w11*w8);
  /* #792: @36 = (@36+@8) */
  w36 += w8;
  /* #793: @9 = (@9-@36) */
  w9 -= w36;
  /* #794: @24 = vertcat(@23, @22, @9) */
  rr=w24;
  *rr++ = w23;
  *rr++ = w22;
  *rr++ = w9;
  /* #795: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) *rr++ = (- *cs++ );
  /* #796: @15 = mac(@28,@24,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w28+j, tt=w24+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #797: @45 = vertcat(@51, @49, @30, @15) */
  rr=w45;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  /* #798: @45 = (-@45) */
  for (i=0, rr=w45, cs=w45; i<7; ++i) *rr++ = (- *cs++ );
  /* #799: @74 = @45[:7] */
  for (rr=w74, ss=w45+0; ss!=w45+7; ss+=1) *rr++ = *ss;
  /* #800: (@44[20, 27, 34, 41, 44, 47, 50] = @74) */
  for (cii=casadi_s31, rr=w44, ss=w74; cii!=casadi_s31+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #801: @51 = zeros(3x1,0nz) */
  /* #802: @49 = zeros(3x1,0nz) */
  /* #803: @30 = zeros(4x1) */
  casadi_clear(w30, 4);
  /* #804: @52 = 00 */
  /* #805: @50 = 00 */
  /* #806: @53 = 00 */
  /* #807: @23 = ones(13x1,1nz) */
  w23 = 1.;
  /* #808: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @22} = vertsplit(@23) */
  w22 = w23;
  /* #809: @23 = vertcat(@52, @50, @53, @22) */
  rr=(&w23);
  *rr++ = w22;
  /* #810: @30 = mac(@35,@23,@30) */
  casadi_mtimes(w35, casadi_s26, (&w23), casadi_s21, w30, casadi_s7, w, 0);
  /* #811: @30 = (@3*@30) */
  for (i=0, rr=w30, cs=w30; i<4; ++i) (*rr++)  = (w3*(*cs++));
  /* #812: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #813: @24 = zeros(3x1) */
  casadi_clear(w24, 3);
  /* #814: @3 = sparsity_cast(@22) */
  casadi_copy((&w22), 1, (&w3));
  /* #815: @24 = mac(@27,@3,@24) */
  casadi_mtimes(w27, casadi_s1, (&w3), casadi_s32, w24, casadi_s27, w, 0);
  /* #816: @3 = @24[2] */
  for (rr=(&w3), ss=w24+2; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #817: @23 = (@11*@3) */
  w23  = (w11*w3);
  /* #818: @37 = (@37*@22) */
  w37 *= w22;
  /* #819: @9 = @24[1] */
  for (rr=(&w9), ss=w24+1; ss!=w24+2; ss+=1) *rr++ = *ss;
  /* #820: @36 = (@12*@9) */
  w36  = (w12*w9);
  /* #821: @37 = (@37+@36) */
  w37 += w36;
  /* #822: @23 = (@23-@37) */
  w23 -= w37;
  /* #823: @40 = (@40*@22) */
  w40 *= w22;
  /* #824: @22 = @24[0] */
  for (rr=(&w22), ss=w24+0; ss!=w24+1; ss+=1) *rr++ = *ss;
  /* #825: @12 = (@12*@22) */
  w12 *= w22;
  /* #826: @40 = (@40+@12) */
  w40 += w12;
  /* #827: @3 = (@10*@3) */
  w3  = (w10*w3);
  /* #828: @40 = (@40-@3) */
  w40 -= w3;
  /* #829: @10 = (@10*@9) */
  w10 *= w9;
  /* #830: @11 = (@11*@22) */
  w11 *= w22;
  /* #831: @10 = (@10-@11) */
  w10 -= w11;
  /* #832: @24 = vertcat(@23, @40, @10) */
  rr=w24;
  *rr++ = w23;
  *rr++ = w40;
  *rr++ = w10;
  /* #833: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) *rr++ = (- *cs++ );
  /* #834: @15 = mac(@28,@24,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w28+j, tt=w24+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #835: @74 = vertcat(@51, @49, @30, @15) */
  rr=w74;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  /* #836: @74 = (-@74) */
  for (i=0, rr=w74, cs=w74; i<7; ++i) *rr++ = (- *cs++ );
  /* #837: @45 = @74[:7] */
  for (rr=w45, ss=w74+0; ss!=w74+7; ss+=1) *rr++ = *ss;
  /* #838: (@44[21, 28, 35, 42, 45, 48, 51] = @45) */
  for (cii=casadi_s33, rr=w44, ss=w45; cii!=casadi_s33+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #839: @75 = @44' */
  casadi_trans(w44,casadi_s35, w75, casadi_s34, iw);
  /* #840: output[1][0] = @75 */
  casadi_copy(w75, 52, res[1]);
  /* #841: @13 = zeros(13x13,13nz) */
  casadi_clear(w13, 13);
  /* #842: @14 = ones(13x1) */
  casadi_fill(w14, 13, 1.);
  /* #843: (@13[:13] = @14) */
  for (rr=w13+0, ss=w14; rr!=w13+13; rr+=1) *rr = *ss++;
  /* #844: @14 = @13' */
  casadi_trans(w13,casadi_s36, w14, casadi_s36, iw);
  /* #845: output[2][0] = @14 */
  casadi_copy(w14, 13, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_jac_x_xdot_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_jac_x_xdot_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_jac_x_xdot_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_jac_x_xdot_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_jac_x_xdot_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_jac_x_xdot_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_jac_x_xdot_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_jac_x_xdot_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_impl_dae_fun_jac_x_xdot_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_impl_dae_fun_jac_x_xdot_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_impl_dae_fun_jac_x_xdot_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_impl_dae_fun_jac_x_xdot_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_impl_dae_fun_jac_x_xdot_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_impl_dae_fun_jac_x_xdot_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s37;
    case 1: return casadi_s37;
    case 2: return casadi_s7;
    case 3: return casadi_s38;
    case 4: return casadi_s38;
    case 5: return casadi_s39;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_impl_dae_fun_jac_x_xdot_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s37;
    case 1: return casadi_s34;
    case 2: return casadi_s36;
    case 3: return casadi_s40;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_jac_x_xdot_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 17;
  if (sz_iw) *sz_iw = 14;
  if (sz_w) *sz_w = 330;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_jac_x_xdot_z_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 17*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 14*sizeof(casadi_int);
  if (sz_w) *sz_w = 330*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
